// Cups - Water element (14 cards)
const SUIT = 'The Suit of Cups belongs to the element of Water, governing emotions, relationships, intuition, imagination, and the inner world of feeling.';
const EL = 'cups';

export const CUPS = [
  { id:'c1', name:'Ace of Cups', num:1, suit:EL, keywords:['new love','emotional beginning','compassion','open heart'],
    symbol:{layers:['outerCircle','wave','innerCircle','dot'],dots:5},
    colors:{primary:'#1a4a7a',secondary:'#3a7aba',accent:'#a0c0e0'},
    deckPosition:'The root energy of the Cups suit. The pure seed of emotional and intuitive potential.',
    suitMeaning:SUIT, numerology:'One is pure potential. In Cups, it is the first stirring of a new emotional experience.',
    astrology:'Associated with the water signs (Cancer, Scorpio, Pisces) in their most receptive, undirected state.',
    foolsJourney:'A new emotional chapter begins. The heart opens to receive what it has been longing for.',
    selfPerception:'You feel emotionally renewed. Something in your heart is waking up after dormancy.',
    worldOutlook:'The world is offering emotional connection, love, or creative inspiration. You need only open your hands to receive.',
    upright:{brief:'Your heart is opening. A new emotional experience arrives.',detail:'The Ace of Cups shows a chalice overflowing with five streams of living water, a dove descending with a communion wafer. This is the purest offering of emotional and spiritual nourishment. A new love, a deepening of compassion, a creative inspiration rooted in feeling.',advice:'Open your heart. Receive what is being offered without calculating the cost. The challenge is vulnerability: this cup can only fill if your hands are open. The caution is against emotional greed. One deep connection is worth more than many shallow ones.'},
    reversed:{brief:'Blocked emotions or refused emotional offering.',detail:'Reversed, the cup tilts and the water spills. An emotional opportunity is being missed or rejected, perhaps because past wounds have made you afraid to feel again.',advice:'If you are blocking, ask what you are protecting. If a wound is leaking, tend it before trying to fill the cup.'},
    scores:{water:10, n1:10}},

  { id:'c2', name:'Two of Cups', num:2, suit:EL, keywords:['partnership','mutual attraction','connection','balance'],
    symbol:{layers:['outerCircle','cross','wave','dottedInner','dot']},
    colors:{primary:'#2a5a8a',secondary:'#4a7aaa',accent:'#a0b8d0'},
    deckPosition:'The second stage: two hearts meet in mutual recognition.',
    suitMeaning:SUIT, numerology:'Two is duality and partnership. In Cups, it is the sacred moment when two emotional worlds connect.',
    astrology:'Venus in Cancer. Love that nurtures and protects both partners equally.',
    foolsJourney:'The heart finds its mirror. Connection is no longer abstract; it is standing in front of you.',
    selfPerception:'You see yourself reflected in another person. Your identity expands through genuine partnership.',
    worldOutlook:'The world contains your counterpart. Logically, you see the value of equal partnership. Emotionally, you feel the magnetism of deep connection.',
    upright:{brief:'A genuine connection. Two hearts meet as equals.',detail:'The Two of Cups shows two figures exchanging chalices, the caduceus of healing rising between them. This is the card of mutual attraction, equal partnership, and the chemistry that arises when two people truly see each other.',advice:'Honor the connection. Meet the other person as an equal. The challenge is maintaining your own identity within the partnership. The caution is against projecting your ideal onto the real person in front of you.'},
    reversed:{brief:'Imbalanced relationship or broken connection.',detail:'Reversed, the exchange becomes one-sided. One person gives while the other takes, or the connection has soured into resentment.',advice:'If the balance is off, name it. Partnerships only survive when both cups are equally full and equally shared.'},
    scores:{water:10, n2:10}},

  { id:'c3', name:'Three of Cups', num:3, suit:EL, keywords:['friendship','community','celebration','shared joy'],
    symbol:{layers:['outerCircle','triangle','wave','dottedRing','dot'],dots:3},
    colors:{primary:'#3a6a9a',secondary:'#5a8aba',accent:'#b0d0f0'},
    deckPosition:'The third stage: emotional connection expands beyond the pair into community.',
    suitMeaning:SUIT, numerology:'Three is expansion and expression. In Cups, it is joy shared and multiplied among friends.',
    astrology:'Mercury in Cancer. Emotional communication that strengthens bonds.',
    foolsJourney:'Love expands from partnership to community. The heart discovers it has room for many.',
    selfPerception:'You see yourself as part of a loving circle. Your identity includes the warmth of friendship and belonging.',
    worldOutlook:'The world is full of people worth celebrating with. Emotionally, you feel the abundance of shared joy.',
    upright:{brief:'Celebrate with your people. Shared joy multiplies.',detail:'The Three of Cups shows three figures dancing together, chalices raised in toast. This is the card of friendship, community gatherings, and the emotional nourishment that comes from being loved by a group.',advice:'Gather your people. Celebrate together. The challenge is making time for connection in a busy life. The caution is against excess: celebration is medicine, not escape.'},
    reversed:{brief:'Social isolation or superficial connections.',detail:'Reversed, the gathering feels hollow. You may be surrounded by people but feeling alone, or avoiding social connection entirely.',advice:'Quality over quantity. If your social life feels empty, seek depth, not breadth. One real conversation outweighs ten surface-level events.'},
    scores:{water:10, n3:10}},

  { id:'c4', name:'Four of Cups', num:4, suit:EL, keywords:['contemplation','apathy','reevaluation','withdrawn'],
    symbol:{layers:['outerCircle','square','wave','innerCircle','dot']},
    colors:{primary:'#2a4a6a',secondary:'#4a6a8a',accent:'#8aaaca'},
    deckPosition:'The fourth stage: emotional stability turns to stagnation or contemplation.',
    suitMeaning:SUIT, numerology:'Four is stability. In Cups, emotional stability can become emotional numbness.',
    astrology:'Moon in Cancer. Deep introspection that can become self-absorption.',
    foolsJourney:'Surrounded by emotional offerings, The Fool turns inward, unable or unwilling to receive what is being offered.',
    selfPerception:'You see yourself as disconnected. Your identity feels flat, uninspired, or dissatisfied despite having enough.',
    worldOutlook:'The world is offering something but you cannot bring yourself to care. Logically, you know you should be grateful. Emotionally, nothing lands.',
    upright:{brief:'Dissatisfaction despite abundance. Look at what is being offered.',detail:'The Four of Cups shows a figure sitting under a tree, arms crossed, staring at three cups on the ground while a hand from a cloud offers a fourth. He does not see it. This card appears when apathy, boredom, or emotional withdrawal prevents you from recognizing opportunities.',advice:'Look up. Something is being offered that you cannot see because you are focused on what you do not have. The challenge is distinguishing genuine contemplation from self-indulgent brooding. The caution is against refusing gifts because they do not match your fantasy.'},
    reversed:{brief:'Emerging from apathy or accepting new emotional input.',detail:'Reversed, you are beginning to notice the offered cup. The fog of disinterest is lifting.',advice:'If motivation is returning, welcome it without judgment. You needed the pause. Now receive.'},
    scores:{water:10, n4:10}},

  { id:'c5', name:'Five of Cups', num:5, suit:EL, keywords:['grief','loss','regret','perspective'],
    symbol:{layers:['outerCircle','wave','dottedInner','triDown','dot'],rotation:0},
    colors:{primary:'#1a2a4a',secondary:'#2a3a5a',accent:'#5a7a9a'},
    deckPosition:'The fifth stage: emotional disruption. Loss arrives and grief must be faced.',
    suitMeaning:SUIT, numerology:'Five is disruption. In Cups, it is the heartbreak that teaches what matters most.',
    astrology:'Mars in Scorpio. The piercing pain that comes from deep emotional investment.',
    foolsJourney:'The heart breaks. But notice: two cups still stand behind the grieving figure. Not everything is lost.',
    selfPerception:'You see yourself through the lens of what you have lost. Your identity feels diminished by grief.',
    worldOutlook:'The world has taken something precious from you. Logically, you know that loss is part of life. Emotionally, the pain is overwhelming.',
    upright:{brief:'Grief is real, but look behind you. Two cups still stand.',detail:'The Five of Cups shows a cloaked figure mourning three spilled cups, unable to see the two full cups standing behind them. This is the card of grief, regret, and the tunnel vision of loss.',advice:'Grieve fully. Do not skip the pain. But when you are ready, turn around. Something survived. The challenge is allowing grief without drowning in it. The caution is against using loss as an identity. You are not defined by what was taken from you.'},
    reversed:{brief:'Beginning to recover from loss or accepting what remains.',detail:'Reversed, the figure begins to turn. The two remaining cups come into view. Recovery is beginning.',advice:'Let the recovery unfold at its own pace. Do not rush back to "fine." But do let yourself notice what survived.'},
    scores:{water:10, n5:10}},

  { id:'c6', name:'Six of Cups', num:6, suit:EL, keywords:['nostalgia','innocence','reunion','childhood'],
    symbol:{layers:['outerCircle','hexagon','wave','dottedRing','dot'],dots:6},
    colors:{primary:'#4a7aaa',secondary:'#7aaad0',accent:'#c0e0ff'},
    deckPosition:'The sixth stage: harmony returns through memory, innocence, and reunion.',
    suitMeaning:SUIT, numerology:'Six restores balance after loss. In Cups, it is the healing that comes from reconnecting with simpler times.',
    astrology:'Sun in Scorpio. Light shining into the depths, illuminating what was hidden in memory.',
    foolsJourney:'After grief, The Fool reconnects with innocence. The past offers gifts if received without clinging.',
    selfPerception:'You see yourself through the eyes of your younger self. Your identity softens with nostalgia and tenderness.',
    worldOutlook:'The world was simpler once, and that simplicity still has wisdom to offer. Emotionally, you feel warmth from memory.',
    upright:{brief:'The past offers a gift. Receive it with the innocence of a child.',detail:'The Six of Cups shows a child offering a cup of flowers to another child in a garden. This is the card of nostalgia, innocence, reunions, and the healing that comes from reconnecting with your roots.',advice:'Allow yourself to revisit the past with tenderness. Accept the gifts it offers. The challenge is enjoying nostalgia without becoming trapped in it. The caution is against idealizing a past that was not as perfect as memory suggests.'},
    reversed:{brief:'Stuck in the past or refusing to grow up.',detail:'Reversed, nostalgia becomes a refuge from the present. You may be clinging to childhood patterns or refusing to face adult reality.',advice:'The past was beautiful, but you do not live there anymore. Bring forward what was good and leave the rest.'},
    scores:{water:10, n6:10}},

  { id:'c7', name:'Seven of Cups', num:7, suit:EL, keywords:['fantasy','illusion','choices','wishful thinking'],
    symbol:{layers:['outerCircle','dottedRing','wave','starSmall','dot'],dots:7},
    colors:{primary:'#3a5a7a',secondary:'#5a7a9a',accent:'#9ab0c8'},
    deckPosition:'The seventh stage: the inner world produces many visions, not all of them real.',
    suitMeaning:SUIT, numerology:'Seven is the number of seeking. In Cups, the search produces many beautiful but potentially illusory options.',
    astrology:'Venus in Scorpio. Deep desires rising to the surface, some genuine, some fantasy.',
    foolsJourney:'The emotional world offers many visions. The Fool must distinguish between genuine desire and fantasy.',
    selfPerception:'You see yourself as someone with many desires and few clear priorities. Your identity fragments across multiple fantasies.',
    worldOutlook:'The world is full of shimmering options. Logically, you know not all of them are real. Emotionally, each one is irresistible.',
    upright:{brief:'Many options appear, but not all are real. Choose wisely.',detail:'The Seven of Cups shows a figure gazing at seven cups floating in clouds, each containing a different prize: jewels, a castle, a snake, a wreath, a dragon, a glowing figure, a veiled head. Some are genuine; some are illusion. This card appears when fantasy is clouding judgment.',advice:'Ground your desires in reality. Ask which of these options you would still want if they required real sacrifice. The challenge is discernment. The caution is against choosing the most dazzling option without checking what is inside.'},
    reversed:{brief:'Clarity cutting through fantasy or overwhelm from too many choices.',detail:'Reversed, the clouds are either clearing (you can finally see what is real) or thickening (overwhelm from decision paralysis).',advice:'If clarity is arriving, act on it before the fog returns. If you are overwhelmed, eliminate options rather than adding more.'},
    scores:{water:10, n7:10}},

  { id:'c8', name:'Eight of Cups', num:8, suit:EL, keywords:['departure','seeking more','emotional courage','walking away'],
    symbol:{layers:['outerCircle','wave','crescent','dottedInner','dot']},
    colors:{primary:'#2a3a5a',secondary:'#4a5a7a',accent:'#7a8aaa'},
    deckPosition:'The eighth stage: the courage to walk away from what no longer fulfills the heart.',
    suitMeaning:SUIT, numerology:'Eight is power and movement. In Cups, it is the strength required to leave behind emotional investments that no longer serve.',
    astrology:'Saturn in Pisces. The discipline to leave what is comfortable for what is meaningful.',
    foolsJourney:'The Fool looks at eight neatly stacked cups and walks away. Not because they are empty, but because they are not enough.',
    selfPerception:'You see yourself as someone who needs more depth. Your identity can no longer be satisfied by what once felt like enough.',
    worldOutlook:'The world has given you much, but something essential is missing. Logically, you see that staying would be settling. Emotionally, leaving is heartbreaking.',
    upright:{brief:'Walk away from what no longer fulfills you. The path ahead holds more.',detail:'The Eight of Cups shows a figure walking away from eight stacked cups, heading toward a mountain under a crescent moon. This is not abandonment; it is the brave recognition that emotional fulfillment requires you to seek beyond what is familiar.',advice:'Leave with gratitude, not bitterness. What you are walking away from served its purpose. The challenge is accepting the loneliness of the path ahead. The caution is against walking away from everything whenever it gets hard. This card is about genuine unfulfillment, not restlessness.'},
    reversed:{brief:'Fear of leaving or aimless wandering.',detail:'Reversed, you either cannot bring yourself to leave what is unfulfilling, or you are wandering without knowing what you seek.',advice:'If you are staying out of fear, name the fear. If you are wandering, define what "enough" would look like before you keep searching.'},
    scores:{water:10, n8:10}},

  { id:'c9', name:'Nine of Cups', num:9, suit:EL, keywords:['satisfaction','contentment','gratitude','wish fulfilled'],
    symbol:{layers:['outerCircle','wave','dottedRing','innerCircle','dotLarge'],dots:9},
    colors:{primary:'#3a6a8a',secondary:'#5a8aaa',accent:'#a0c8e0'},
    deckPosition:'The ninth stage: emotional fulfillment. The wish card.',
    suitMeaning:SUIT, numerology:'Nine is near completion. In Cups, it is the deep satisfaction of emotional wishes fulfilled.',
    astrology:'Jupiter in Pisces. Emotional abundance and the generosity of spirit.',
    foolsJourney:'The Fool has found what the heart truly wanted. Nine cups gleam in an arc of fulfillment.',
    selfPerception:'You see yourself as fortunate and satisfied. Your identity rests comfortably in gratitude.',
    worldOutlook:'The world has given you what you asked for. Logically, you see the results of emotional investment. Emotionally, you feel deeply content.',
    upright:{brief:'Your wish is granted. Savor the satisfaction.',detail:'The Nine of Cups, known as the "wish card," shows a figure seated before nine golden cups, arms folded in satisfaction. What you wished for emotionally is arriving or has arrived. This is genuine contentment, not fleeting pleasure.',advice:'Receive it. Do not deflect, minimize, or immediately wish for more. Sit with the satisfaction. The challenge is allowing yourself to be happy without waiting for the other shoe to drop. The caution is against smugness: gratitude is attractive, complacency is not.'},
    reversed:{brief:'Unfulfilled wishes or shallow satisfaction.',detail:'Reversed, the wish either has not arrived or its arrival reveals that it is not what you truly wanted.',advice:'If the wish disappoints, the problem was the wish, not the universe. Go deeper. What do you actually need beneath what you thought you wanted?'},
    scores:{water:10, n9:10}},

  { id:'c10', name:'Ten of Cups', num:10, suit:EL, keywords:['harmony','family','emotional fulfillment','lasting joy'],
    symbol:{layers:['outerCircle','wave','hexagon','dottedRing','innerCircle','dotLarge'],dots:10},
    colors:{primary:'#4a8aaa',secondary:'#7ab0d0',accent:'#c0e8ff'},
    deckPosition:'The tenth and final numbered stage: the emotional journey reaches its fullest expression in shared joy.',
    suitMeaning:SUIT, numerology:'Ten completes the cycle. In Cups, it is the rainbow after the storm, the family gathered in harmony.',
    astrology:'Mars in Pisces. Passionate devotion channeled into lasting emotional bonds.',
    foolsJourney:'The emotional journey reaches its summit. Love is not just felt but lived, shared, and sustained.',
    selfPerception:'You see yourself as part of a loving whole. Your identity is interwoven with the people you cherish.',
    worldOutlook:'The world is a good place when love is real and sustained. Logically, you see the fruit of emotional investment. Emotionally, you feel complete.',
    upright:{brief:'Lasting emotional fulfillment. Love sustained and shared.',detail:'The Ten of Cups shows a family standing beneath a rainbow of ten cups, arms raised in joy. This is not momentary happiness but sustained emotional fulfillment: the kind that comes from building real relationships over time.',advice:'Nurture what you have. This level of emotional fulfillment is rare and precious. The challenge is not taking it for granted. The caution is against perfection: no family or relationship is without friction. The rainbow does not erase the rain; it follows it.'},
    reversed:{brief:'Broken harmony or unattainable ideals of happiness.',detail:'Reversed, the rainbow fades. Family tensions, broken bonds, or impossible standards of happiness mar what could be beautiful.',advice:'If harmony is disrupted, address the real issue, not the surface symptom. If your ideal of happiness is unreachable, lower the bar from "perfect" to "real."'},
    scores:{water:10, n10:10}},

  { id:'c11', name:'Page of Cups', num:11, suit:EL, keywords:['creative message','emotional curiosity','imagination','tender beginning'],
    symbol:{layers:['outerCircle','wave','starSmall','dot']},
    colors:{primary:'#3a7aaa',secondary:'#5a9aca',accent:'#a0d0f0'},
    deckPosition:'The Page is the student of water: tender, imaginative, and emotionally open.',
    suitMeaning:SUIT, numerology:'Pages represent the beginning of a new relationship with their element. In Cups, it is the child discovering the depth of feeling.',
    astrology:'Earth of Water. The grounding force that gives emotional experience a starting point.',
    foolsJourney:'A new relationship with emotion and intuition begins. The heart approaches with wonder rather than experience.',
    selfPerception:'You see yourself as emotionally open and curious. Your identity is soft, receptive, and imaginative.',
    worldOutlook:'The world is full of emotional beauty waiting to be discovered. You see with the eyes of wonder.',
    upright:{brief:'A tender emotional message or creative inspiration arrives.',detail:'The Page of Cups stands at the shore, surprised by a fish popping out of his cup. This card brings unexpected emotional messages, creative inspirations, or the beginning of a new emotional chapter characterized by wonder.',advice:'Stay open to surprises. Do not dismiss the intuitive nudge or the unexpected feeling. The challenge is staying receptive without becoming naive. The caution is against emotional immaturity: wonder is beautiful, but it needs to mature.'},
    reversed:{brief:'Emotional immaturity or creative blocks.',detail:'Reversed, the Page either refuses to feel or feels everything without processing.',advice:'If blocked, return to play. Creativity follows joy, not pressure. If overwhelmed, learn to hold emotions rather than being held by them.'},
    scores:{water:10, page:10}},

  { id:'c12', name:'Knight of Cups', num:12, suit:EL, keywords:['romance','charm','following the heart','idealism'],
    symbol:{layers:['outerCircle','wave','triUp','diamond','dot']},
    colors:{primary:'#4a6a9a',secondary:'#6a8aba',accent:'#b0c8e0'},
    deckPosition:'The Knight is water in motion: romantic, idealistic, and driven by the heart.',
    suitMeaning:SUIT, numerology:'Knights represent active pursuit. In Cups, it is the romantic quest for emotional truth.',
    astrology:'Air of Water. The intellectualization of emotion, the poet and the dreamer.',
    foolsJourney:'The heart sets out on a quest. Emotion becomes purpose, and the Knight follows it with devotion.',
    selfPerception:'You see yourself as a romantic and idealist. Your identity is tied to the pursuit of beauty and emotional authenticity.',
    worldOutlook:'The world deserves to be approached with grace, beauty, and emotional honesty.',
    upright:{brief:'Follow your heart with grace. The romantic quest has begun.',detail:'The Knight of Cups rides slowly toward you, offering a cup like a proposal. He is the poet, the lover, the artist who follows emotion as his guiding star. This card appears when the heart is leading and asking you to trust it.',advice:'Follow the feeling with sincerity. Approach the situation with grace and emotional openness. The challenge is balancing idealism with reality. The caution is against falling in love with the idea of love rather than the person in front of you.'},
    reversed:{brief:'Unrealistic expectations or emotional manipulation.',detail:'Reversed, the Knight\'s romanticism becomes escapism or his charm becomes manipulation.',advice:'If you are chasing a fantasy, land. If you are using charm to get what you want, check your sincerity.'},
    scores:{water:10, knight:10}},

  { id:'c13', name:'Queen of Cups', num:13, suit:EL, keywords:['emotional depth','compassion','intuition','empathy'],
    symbol:{layers:['outerCircle','wave','innerCircle','crescent','dotLarge']},
    colors:{primary:'#2a4a7a',secondary:'#4a6a9a',accent:'#8ab0d0'},
    deckPosition:'The Queen has mastered water from within. She feels deeply without drowning.',
    suitMeaning:SUIT, numerology:'Queens represent internal mastery. In Cups, it is the ability to hold vast emotional depth with grace.',
    astrology:'Water of Water. Pure emotional intelligence, the healer and the empath.',
    foolsJourney:'Emotion has been internalized and mastered. The Queen does not suppress feeling; she holds it with the skill of a vessel that never overflows.',
    selfPerception:'You see yourself as someone who understands the heart. Your identity is rooted in compassion, intuition, and emotional wisdom.',
    worldOutlook:'The world needs more compassion and emotional depth. You see beneath the surface of every situation.',
    upright:{brief:'Trust your emotional wisdom. Hold space with compassion.',detail:'The Queen of Cups sits by the sea, holding an ornate closed cup. She is the empathic healer, the counselor, the one who feels everything but is not destroyed by it. Her cup is closed because she has learned that not all emotions need to be shared.',advice:'Trust your intuition. Offer compassion without losing yourself. The challenge is maintaining boundaries while remaining emotionally available. The caution is against absorbing others\' emotions as your own. Empathy without boundaries becomes codependency.'},
    reversed:{brief:'Emotional overwhelm or codependency.',detail:'Reversed, the Queen drowns in the feelings she usually masters. The boundary between self and other dissolves.',advice:'If you are overwhelmed, pull back. Your compassion is a gift, but it requires the container of healthy boundaries to function.'},
    scores:{water:10, queen:10}},

  { id:'c14', name:'King of Cups', num:14, suit:EL, keywords:['emotional maturity','diplomacy','calm authority','wisdom'],
    symbol:{layers:['outerCircle','wave','cross','innerCircle','hexagon','dotLarge']},
    colors:{primary:'#1a3a5a',secondary:'#3a5a7a',accent:'#7a9aba'},
    deckPosition:'The King is the external master of water: emotionally wise, diplomatically skilled, and calmly authoritative.',
    suitMeaning:SUIT, numerology:'Kings represent external mastery. In Cups, it is the leader who governs with emotional intelligence.',
    astrology:'Fire of Water. Passion channeled through emotional mastery and wise leadership.',
    foolsJourney:'Water has been fully mastered. The King does not suppress emotion; he channels it into wise leadership and compassionate authority.',
    selfPerception:'You see yourself as emotionally mature and balanced. Your identity includes the ability to feel deeply while acting wisely.',
    worldOutlook:'The world needs leaders who can think and feel. Logically, you see the value of emotional intelligence. Emotionally, you remain calm in storms.',
    upright:{brief:'Lead with emotional intelligence. Calm seas reflect deep waters.',detail:'The King of Cups sits on his throne amid a turbulent sea, yet he remains perfectly calm. A fish leaps at his feet and a ship sails in the background. He is the master of the emotional realm, able to feel everything without being controlled by anything.',advice:'Govern with both head and heart. Your emotional maturity is your greatest leadership asset. The challenge is remaining open while maintaining composure. The caution is against emotional repression disguised as maturity. Calm is not the absence of feeling.'},
    reversed:{brief:'Emotional manipulation or suppressed feelings creating problems.',detail:'Reversed, the King either uses emotional intelligence to manipulate, or his calm exterior hides a sea of unexpressed turmoil.',advice:'If you are manipulating, stop. Emotional intelligence used for control is the most dangerous kind. If you are suppressing, let yourself feel. The sea cannot be bottled forever.'},
    scores:{water:10, king:10}}
];
