// Major Arcana Part 2 (cards 11-21)
export const MAJOR_ARCANA_P2 = [
  { id:'m11', name:'Justice', num:11, suit:'major',
    keywords:['fairness','truth','accountability','cause and effect'],
    symbol:{layers:['outerCircle','diamond','cross','dottedInner','dot']},
    colors:{primary:'#8b0000',secondary:'#b22222',accent:'#c8a45c'},
    deckPosition:'Card XI. She sits between two pillars, sword raised in the right hand and scales balanced in the left.',
    suitMeaning:'As a Major Arcana card, Justice represents the universal law of cause and effect.',
    numerology:'Eleven is a master number signifying higher truth, spiritual insight, and the clarity that comes from seeing beyond personal bias.',
    astrology:'Ruled by Libra, the sign of balance, fairness, and partnership. Libra weighs all sides before rendering judgment.',
    foolsJourney:'Having accepted that fate exists (Wheel of Fortune), The Fool now learns that personal choices also have consequences. Justice teaches accountability.',
    selfPerception:'You see yourself as someone who values fairness above comfort. Your identity is shaped by your relationship with truth, even when it is inconvenient.',
    worldOutlook:'The world operates on cause and effect. Logically, you see every action producing an inevitable consequence. Emotionally, you carry a deep need for things to be fair.',
    upright:{brief:'Truth and accountability. The consequences of past choices arrive.',detail:'Justice demands honest accounting. This card appears when the results of past decisions are coming due, when a legal or ethical matter requires resolution, or when you must make a choice based on principle rather than preference. The sword cuts through illusion; the scales weigh without bias.',advice:'Be scrupulously honest with yourself and others. Accept responsibility for your part in the current situation. The challenge is releasing attachment to the outcome you want in favor of the outcome that is fair. The caution is against using "justice" as a mask for vengeance.'},
    reversed:{brief:'Dishonesty, avoidance of accountability, or unfair judgment.',detail:'Reversed, Justice is blindfolded rather than clear-eyed. There is dishonesty, either yours or someone else\'s. Accountability is being dodged, the scales are rigged, or judgment is being rendered without all the facts.',advice:'If you are avoiding consequences, they will find you eventually. Better to face them now. If you feel judged unfairly, gather your evidence and present it calmly. The caution is against self-righteousness: being wronged does not make you right about everything.'},
    scores:{spirit:10, m11:10}},

  { id:'m12', name:'The Hanged Man', num:12, suit:'major',
    keywords:['surrender','new perspective','pause','sacrifice'],
    symbol:{layers:['outerCircle','triDown','dottedRing','innerCircle','dot'],rotation:180},
    colors:{primary:'#2a3a6a',secondary:'#4a5a9a',accent:'#7aa0d0'},
    deckPosition:'Card XII. A figure hangs upside down from a living tree, suspended by one foot, face serene rather than distressed.',
    suitMeaning:'As a Major Arcana card, The Hanged Man represents the transformative power of voluntary surrender.',
    numerology:'Twelve completes the cycle of the zodiac. It represents the perspective that comes from seeing all sides, the wisdom of suspended action.',
    astrology:'Ruled by Neptune, planet of dissolution, dreams, transcendence, and the surrender of ego to something greater.',
    foolsJourney:'After encountering Justice, The Fool learns that some situations cannot be resolved through action. The Hanged Man teaches the paradox that letting go creates more progress than holding on.',
    selfPerception:'You see yourself as someone who is willing to sacrifice comfort for insight. Your identity may feel suspended or uncertain, but this discomfort is producing a new way of seeing.',
    worldOutlook:'The world looks different when viewed from an unexpected angle. Logically, you recognize that your current framework may be incomplete. Emotionally, you feel the strange peace that comes with surrender.',
    upright:{brief:'Surrender the need to act. See from a completely new angle.',detail:'The Hanged Man is not a victim. He chose this suspension. By voluntarily releasing control, he sees the world from an inverted perspective that reveals truths invisible from the ground. This card appears when pushing harder will not help, when the answer requires you to stop, invert your assumptions, and see differently.',advice:'Stop trying to fix it. Let go of the timeline. Something valuable is gestating in this pause, but it requires your willingness to be uncomfortable. The challenge is tolerating the uncertainty. The caution is against confusing genuine surrender with passive avoidance.'},
    reversed:{brief:'Stalling, martyrdom, or refusing to see differently.',detail:'Reversed, The Hanged Man is stuck rather than surrendered. You may be resisting the necessary pause, insisting on action when stillness is required, or performing sacrifice for attention rather than insight.',advice:'Ask whether you are truly letting go or merely stuck. If you are resisting the pause, something in you knows that the shift in perspective will change everything, and that scares you. Let it.'},
    scores:{spirit:10, m12:10}},

  { id:'m13', name:'Death', num:13, suit:'major',
    keywords:['transformation','ending','release','rebirth'],
    symbol:{layers:['outerCircle','rays','triDown','dottedInner','dot'],rayCount:5,rotation:180},
    colors:{primary:'#1a1a2e',secondary:'#2d2d4e',accent:'#e0c97a'},
    deckPosition:'Card XIII. The skeleton rider moves through a landscape where kings and commoners alike must kneel. A white rose banner promises renewal.',
    suitMeaning:'As a Major Arcana card, Death represents the universal principle that transformation requires the complete ending of what came before.',
    numerology:'Thirteen carries the energy of radical transformation. It breaks the stability of twelve, forcing evolution through destruction of the obsolete.',
    astrology:'Ruled by Scorpio, the sign of depth, transformation, power, and the cycle of death and rebirth. Scorpio goes where others fear to look.',
    foolsJourney:'After surrendering perspective (The Hanged Man), The Fool encounters the reality that some things must die for new life to emerge. Death teaches that clinging to what has ended creates suffering.',
    selfPerception:'You see yourself in transition. The person you were is dissolving and the person you are becoming has not yet fully arrived. This is disorienting but necessary.',
    worldOutlook:'The world is in constant transformation. Logically, you recognize that nothing is permanent. Emotionally, you feel the grief of endings and the quiet stirring of what comes next.',
    upright:{brief:'Something must end completely for transformation to begin.',detail:'Death does not mean physical death. It is the card of absolute transformation, the kind that cannot be undone or reversed. A chapter is closing. A relationship, identity, belief system, or way of life has reached its conclusion. The white rose on the banner promises that from this ending, new life will emerge, but only if you let the old form die completely.',advice:'Let it go. Do not try to resurrect what has ended. Grieve fully, then release. The challenge is accepting that you cannot take the old self into the new chapter. The caution is against premature closure: let the process complete before rushing into what is next.'},
    reversed:{brief:'Resistance to necessary change or fear of letting go.',detail:'Reversed, Death signals that you are clinging to something that has already ended. The transformation is happening whether you cooperate or not, but your resistance is making it slower and more painful.',advice:'What are you holding onto that has already died? A relationship, an identity, a belief? Your grip is not keeping it alive. It is keeping you trapped. Release is not betrayal. It is survival.'},
    scores:{spirit:10, m13:10}},

  { id:'m14', name:'Temperance', num:14, suit:'major',
    keywords:['balance','moderation','patience','alchemy'],
    symbol:{layers:['outerCircle','triUp','triDown','dottedRing','innerCircle','dot'],dots:7},
    colors:{primary:'#4a7a5a',secondary:'#7aaa8a',accent:'#c8a45c'},
    deckPosition:'Card XIV. An angel stands with one foot on land and one in water, pouring liquid between two cups in an endless flow.',
    suitMeaning:'As a Major Arcana card, Temperance represents the art of integration, of blending opposites into something greater than either.',
    numerology:'Fourteen reduces to five (1+4=5), the number of challenge and adaptation, but at a higher octave. It is the conscious integration of what five disrupts.',
    astrology:'Ruled by Sagittarius, the sign of seeking, synthesis, and the quest for meaning across cultures and philosophies.',
    foolsJourney:'After the death of the old self (Death), The Fool must learn to integrate the new with what survived. Temperance teaches that healing is an art of patient blending.',
    selfPerception:'You see yourself as someone who bridges contradictions. Your identity holds multiple truths without needing to choose between them.',
    worldOutlook:'The world is best navigated through balance and patience. Logically, you understand that extremes are unsustainable. Emotionally, you seek the calm center between opposing pulls.',
    upright:{brief:'Blend opposites with patience. The middle path holds the answer.',detail:'Temperance is the art of alchemy. The angel pours water between cups without spilling a drop, demonstrating that opposing forces can be combined into something entirely new. This card appears when moderation, patience, and the careful integration of different parts of your life are needed.',advice:'Do not rush. The blending of opposites takes time and precision. Find the middle path between extremes. The challenge is patience when you want immediate resolution. The caution is against mistaking compromise for integration: true temperance creates something new, not a watered-down version of two things.'},
    reversed:{brief:'Imbalance, excess, or forced incompatibility.',detail:'Reversed, Temperance loses its balance. You may be living in excess, burning out from overwork, or trying to force two incompatible elements to merge. The flow between the cups has been disrupted.',advice:'Where in your life are you out of balance? Something is taking too much of your energy while something else is being starved. Restore the flow. The caution is against pushing through imbalance with willpower. That is The Chariot, not Temperance.'},
    scores:{spirit:10, m14:10}},

  { id:'m15', name:'The Devil', num:15, suit:'major',
    keywords:['shadow','bondage','materialism','temptation'],
    symbol:{layers:['outerCircle','star5','dottedInner','crossSmall','dot'],rotation:180},
    colors:{primary:'#1a0a0a',secondary:'#3a1a1a',accent:'#8b0000'},
    deckPosition:'Card XV. A horned figure sits above two chained humans who could remove their chains if they chose. The bondage is voluntary.',
    suitMeaning:'As a Major Arcana card, The Devil represents the shadow self and the illusions that keep us trapped.',
    numerology:'Fifteen reduces to six (1+5=6), echoing The Lovers but in shadow form. Where The Lovers choose freely, The Devil presents choice as an illusion.',
    astrology:'Ruled by Capricorn, the sign of ambition, structure, and the shadow side of material achievement.',
    foolsJourney:'The Fool, having found balance (Temperance), must now confront the parts of the self that resist balance. The Devil is the shadow, the denied desires and fears.',
    selfPerception:'You see yourself as trapped, but the truth is more complex. Part of you is choosing the chains because they feel familiar. Your identity may be entangled with patterns you claim to hate.',
    worldOutlook:'The world tempts with quick fixes and comfortable lies. Logically, you can see the trap. Emotionally, the pull of habit, addiction, or unhealthy attachment is powerful.',
    upright:{brief:'Confront the chains you have chosen. They can be removed.',detail:'The Devil is the most misunderstood card in the deck. It is not evil. It is awareness of the shadow. The two figures chained to the pedestal could slip their chains off at any time, but they do not, because the bondage serves some hidden purpose. This card appears when addiction, toxic attachment, materialism, or self-destructive patterns need to be honestly acknowledged.',advice:'Name the pattern. Addiction, codependency, workaholism, self-sabotage. You cannot change what you will not see. The challenge is honesty about what you are getting from the pattern. The caution is against projecting the shadow onto others: the devil you need to face is your own.'},
    reversed:{brief:'Breaking free from bondage or deeper descent into denial.',detail:'Reversed, The Devil signals either a breakthrough, the moment you finally see the chains and choose to remove them, or a deeper descent into denial where you insist you are free while tightening your own bonds.',advice:'If you are breaking free, do not look back. If you are still denying, ask yourself: what would happen if I admitted the truth? The answer is usually less terrifying than the question.'},
    scores:{spirit:10, m15:10}},

  { id:'m16', name:'The Tower', num:16, suit:'major',
    keywords:['upheaval','revelation','sudden change','liberation'],
    symbol:{layers:['outerCircle','rays','triDown','cross','dot'],rayCount:8,rotation:180},
    colors:{primary:'#2a0a1a',secondary:'#5a1a3a',accent:'#ff4500'},
    deckPosition:'Card XVI. Lightning strikes a tower, shattering its crown. Figures fall from the structure into the unknown.',
    suitMeaning:'As a Major Arcana card, The Tower represents the destruction of false structures by the force of truth.',
    numerology:'Sixteen reduces to seven (1+6=7), the number of spiritual seeking. The Tower is the crisis that forces the seeking.',
    astrology:'Ruled by Mars, planet of war, aggression, and the force that tears down what is no longer structurally sound.',
    foolsJourney:'The Fool, having confronted the shadow (The Devil), now experiences the collapse of structures built on false foundations. The Tower destroys what was never real.',
    selfPerception:'You feel shattered. Your sense of identity may be in crisis as beliefs or structures you depended on collapse around you.',
    worldOutlook:'The world is not what you thought it was. Logically, you recognize that the collapse was inevitable. Emotionally, you are in shock, but beneath the shock, there may be relief.',
    upright:{brief:'A structure built on false foundations collapses. Truth liberates.',detail:'The Tower is the lightning bolt of truth that destroys everything built on lies, denial, or shaky foundations. It is sudden, shocking, and cannot be prevented. But look closely: the lightning also illuminates. In the flash of destruction, you see clearly what was hidden. This is not punishment. It is liberation from a prison you did not know you were in.',advice:'Do not try to rebuild what has fallen. It fell because it was not structurally sound. Let the rubble settle before you start again. The challenge is trusting that this destruction serves a purpose. The caution is against clinging to the debris.'},
    reversed:{brief:'Delayed inevitable collapse or internal upheaval.',detail:'Reversed, The Tower is shaking but has not yet fallen. You may be aware that a collapse is coming but are trying to delay it, or the upheaval is internal rather than external, a slow crumbling of beliefs rather than a dramatic crisis.',advice:'If you know the structure is unstable, take it down yourself rather than waiting for lightning. Controlled demolition is less traumatic than unexpected collapse.'},
    scores:{spirit:10, m16:10}},

  { id:'m17', name:'The Star', num:17, suit:'major',
    keywords:['hope','healing','inspiration','serenity'],
    symbol:{layers:['outerCircle','star6','dottedRing','rays','innerCircle','dot'],dots:8,rayCount:8},
    colors:{primary:'#1a3a5a',secondary:'#3a6a9a',accent:'#f5e6c8'},
    deckPosition:'Card XVII. A naked woman kneels by a pool, pouring water onto the earth and into the pool. Eight stars shine above her.',
    suitMeaning:'As a Major Arcana card, The Star represents the healing and hope that follow catastrophe.',
    numerology:'Seventeen reduces to eight (1+7=8), the number of balance and infinite flow. After destruction, regeneration begins.',
    astrology:'Ruled by Aquarius, the sign of vision, humanitarianism, and the pouring forth of knowledge and healing for the collective.',
    foolsJourney:'After the destruction of The Tower, The Fool is stripped bare but alive. The Star provides healing, hope, and the first glimpse of a new purpose.',
    selfPerception:'You see yourself as someone who has survived. Your identity is being rebuilt from authenticity rather than fear. There is a vulnerability that feels sacred rather than shameful.',
    worldOutlook:'The world is healing. Logically, you see that destruction cleared the way for something better. Emotionally, you feel a quiet faith that you had forgotten was possible.',
    upright:{brief:'After the storm, healing arrives. Hope is not naive; it is earned.',detail:'The Star appears after The Tower to say: you survived. Now heal. The woman pours water with both hands, one stream into the pool of the unconscious, one onto the earth of the material world. She is healing both inner and outer reality simultaneously. This card is the most gentle in the deck.',advice:'Allow yourself to be vulnerable. Receive the healing that is being offered. Share your gifts without calculating the return. The challenge is trusting hope after devastation. The caution is against rushing the healing to get to the next thing. Stay with the peace.'},
    reversed:{brief:'Loss of faith or disconnection from hope.',detail:'Reversed, The Star dims. You may have lost faith after too many disappointments, or you may be refusing the healing process, pushing through pain rather than allowing it to be tended.',advice:'If hope feels impossible, start smaller. One small act of beauty. One honest moment. Hope is not a grand gesture; it is the quiet choice to remain open. The caution is against cynicism disguised as realism.'},
    scores:{spirit:10, m17:10}},

  { id:'m18', name:'The Moon', num:18, suit:'major',
    keywords:['illusion','fear','the unconscious','intuition'],
    symbol:{layers:['outerCircle','crescent','dottedRing','wave','dot'],dots:6},
    colors:{primary:'#0d1a2e',secondary:'#1a2a4e',accent:'#7a9ac0'},
    deckPosition:'Card XVIII. A moon shines over a path that winds between two towers, past a dog and a wolf, into unknown darkness.',
    suitMeaning:'As a Major Arcana card, The Moon represents the territory of the unconscious mind, where nothing is as it appears.',
    numerology:'Eighteen reduces to nine (1+8=9), the number of completion through inner work. The Moon is the final inner challenge before dawn.',
    astrology:'Ruled by Pisces, the sign of dreams, the unconscious, spiritual dissolution, and the boundary between reality and illusion.',
    foolsJourney:'The Fool, having been healed by The Star, must now walk through the landscape of the unconscious. The Moon is the dark night of the soul, the territory of dreams and fears.',
    selfPerception:'You see yourself through a distorted lens. Your identity feels uncertain, shifting between intuitive knowing and paralyzing confusion.',
    worldOutlook:'The world is not what it appears to be. Logically, you know you cannot trust your perceptions right now. Emotionally, you feel the pull of deep fears and ancient patterns rising from the unconscious.',
    upright:{brief:'Navigate the unconscious. Not everything you see is real.',detail:'The Moon illuminates a deceptive landscape. Shadows move, shapes shift, and the path forward is unclear. This card appears when anxiety, confusion, illusion, or unconscious fears are distorting your perception. The challenge is not to eliminate the uncertainty but to walk through it without losing yourself.',advice:'Do not make major decisions in moonlight. Wait for dawn. Pay attention to dreams and recurring feelings; they carry information, but they are not literal. The challenge is maintaining your center when everything feels unstable. The caution is against believing your fears are facts.'},
    reversed:{brief:'Illusions clearing or repressed fears breaking through.',detail:'Reversed, The Moon may indicate that confusion is lifting and you are beginning to see clearly. Alternatively, repressed fears and anxieties may be erupting into consciousness, demanding attention.',advice:'If clarity is arriving, trust it. If fears are surfacing, let them come. What rises from the unconscious needs to be seen, not shoved back down. The caution is against overreacting to what surfaces: acknowledge it, do not obey it blindly.'},
    scores:{spirit:10, m18:10}},

  { id:'m19', name:'The Sun', num:19, suit:'major',
    keywords:['joy','success','vitality','clarity'],
    symbol:{layers:['outerCircle','rays','innerCircle','dottedRing','dotLarge'],rayCount:12},
    colors:{primary:'#d4a017',secondary:'#f0c040',accent:'#fff8dc'},
    deckPosition:'Card XIX. A child rides a white horse under a blazing sun, arms wide open, sunflowers blooming behind.',
    suitMeaning:'As a Major Arcana card, The Sun represents the universal experience of joy, clarity, and the fullness of being.',
    numerology:'Nineteen reduces to one (1+9=10, 1+0=1), a return to the beginning but with the wisdom of the entire journey. It is The Magician illuminated by experience.',
    astrology:'Ruled by the Sun itself, the center of the solar system, representing the conscious self, vitality, and the light of awareness.',
    foolsJourney:'After the darkness of The Moon, The Fool emerges into brilliant daylight. The Sun is the reward of having walked through the unconscious without being consumed by it.',
    selfPerception:'You see yourself clearly and joyfully. Your identity is radiant, authentic, and unapologetic. The child on the horse has nothing to hide.',
    worldOutlook:'The world is bright and good. Logically, you see things as they are, without distortion. Emotionally, you feel genuine happiness and gratitude.',
    upright:{brief:'Pure joy and clarity. Everything is illuminated.',detail:'The Sun is the most positive card in the deck. There is no hidden meaning, no warning, no complexity. The Sun shines and everything it touches is warm, clear, and alive. This card appears when success, happiness, vitality, and truth are radiating through your life.',advice:'Celebrate. Share your joy. Let others see your authentic self without dimming your light for their comfort. The challenge is accepting that you deserve this. The caution is slight: do not forget that The Moon exists. Joy is real, but it is not permanent.'},
    reversed:{brief:'Dimmed joy or difficulty accepting happiness.',detail:'Reversed, The Sun still shines, but clouds partially obscure it. Joy is present but you are struggling to feel it, perhaps due to depression, self-doubt, or the belief that happiness cannot last.',advice:'The light is still there. If you cannot feel it, ask what is blocking your access. Childhood wounds around worthiness often surface here. You are allowed to be happy.'},
    scores:{spirit:10, m19:10}},

  { id:'m20', name:'Judgement', num:20, suit:'major',
    keywords:['reckoning','renewal','calling','absolution'],
    symbol:{layers:['outerCircle','cross','rays','triUp','dottedInner','dot'],rayCount:6},
    colors:{primary:'#4a2a4a',secondary:'#7a4a7a',accent:'#c8a45c'},
    deckPosition:'Card XX. An angel blows a trumpet from the clouds. The dead rise from their coffins, arms outstretched, answering the call.',
    suitMeaning:'As a Major Arcana card, Judgement represents the great reckoning and the soul\'s response to its true calling.',
    numerology:'Twenty reduces to two (2+0=2), echoing The High Priestess. Where she holds hidden knowledge, Judgement reveals it to the world.',
    astrology:'Ruled by Pluto, planet of deep transformation, collective unconscious, death and rebirth at the soul level.',
    foolsJourney:'The Fool hears the final trumpet. Everything experienced on the journey is being called to account. Judgement asks: knowing everything you now know, who are you choosing to become?',
    selfPerception:'You see yourself at a crossroads of identity. The old self is being called to rise, to be evaluated honestly, and to be either released or renewed.',
    worldOutlook:'The world is calling you to a higher purpose. Logically, you see the need for honest self-assessment. Emotionally, you feel the urgency of a calling that will not wait.',
    upright:{brief:'Answer the call. Rise to who you are meant to become.',detail:'Judgement is the moment of reckoning, not punishment, but honest evaluation. The trumpet sounds and the dead rise, not to be judged by an external authority, but to judge themselves, to see clearly what they have done and who they have become, and to choose consciously what comes next.',advice:'Respond to the calling. Forgive yourself for past mistakes. Let the person you have become step forward without dragging the guilt of who you used to be. The challenge is radical self-honesty. The caution is against judging others while avoiding your own reckoning.'},
    reversed:{brief:'Self-doubt blocking renewal or refusal to hear the call.',detail:'Reversed, Judgement indicates that you are hearing the call but refusing to answer, either because you do not believe you are worthy or because the answer demands changes you are afraid to make.',advice:'The trumpet is sounding for you. Ignoring it will not silence it. Whatever you are afraid to face about yourself, the facing of it is the liberation. Stop waiting to feel ready.'},
    scores:{spirit:10, m20:10}},

  { id:'m21', name:'The World', num:21, suit:'major',
    keywords:['completion','wholeness','integration','accomplishment'],
    symbol:{layers:['outerCircle','hexagon','star6','innerCircle','dottedRing','dotLarge'],dots:12},
    colors:{primary:'#1a3a4a',secondary:'#3a6a7a',accent:'#c8a45c'},
    deckPosition:'Card XXI, the final numbered card of the Major Arcana. A dancer floats within a wreath of victory, the four living creatures of the zodiac at each corner.',
    suitMeaning:'As a Major Arcana card, The World represents the completion of the soul\'s journey and the integration of all lessons learned.',
    numerology:'Twenty-one reduces to three (2+1=3), echoing The Empress. Where The Empress creates new life, The World completes the cycle and prepares for the next one.',
    astrology:'Ruled by Saturn, the planet of time, mastery, structure, and the final exam. Saturn rewards the work of the entire journey.',
    foolsJourney:'The Fool has completed the journey. Every lesson has been integrated. The World is both the end and the new beginning, as The Fool prepares to step off the cliff once more, this time with wisdom.',
    selfPerception:'You see yourself as whole. Not perfect, but complete. Every experience, every wound, every triumph has been woven into the fabric of who you are.',
    worldOutlook:'The world is a dance and you are finally dancing in rhythm with it. Logically, you see the interconnection of all things. Emotionally, you feel a deep, earned peace.',
    upright:{brief:'Completion. You have arrived. The cycle is fulfilled.',detail:'The World dancer floats in the center of a laurel wreath, the symbol of victory. In her hands she holds two wands, representing the balance of active and receptive forces. This is the card of true accomplishment, not the kind that comes from ticking a box, but the kind that comes from integrating every lesson of the journey. You are whole.',advice:'Celebrate this completion. Allow yourself to feel the fullness of what you have achieved and who you have become. Then prepare for the next cycle, because The Fool always steps off the cliff again. The challenge is avoiding the temptation to cling to this summit. The caution is against believing the journey is over. Completion is a doorway, not a destination.'},
    reversed:{brief:'Near completion or reluctance to close a chapter.',detail:'Reversed, The World indicates that you are almost there but something remains unfinished. A loose end, an unlearned lesson, or a reluctance to step into the completion that awaits you. You may be dragging your feet because finishing means beginning again.',advice:'What is the final piece? It is usually something small that you have been avoiding. Complete it. Close the chapter. The next one cannot begin until you do.'},
    scores:{spirit:10, m21:10}}
];
