// Major Arcana (22 cards) - The Fool's Journey through life's great archetypes
export const MAJOR_ARCANA = [
  { id:'m0', name:'The Fool', num:0, suit:'major',
    keywords:['innocence','leap of faith','new beginning','spontaneity'],
    symbol:{layers:['outerCircle','spiral','dottedRing','dot'],dots:7},
    colors:{primary:'#c8a45c',secondary:'#e0c97a',accent:'#f5e6c8'},
    deckPosition:'Card 0, the unnumbered origin point of the Major Arcana. The Fool stands outside the sequence, both before and after every other card.',
    suitMeaning:'As a Major Arcana card, The Fool represents a core life archetype rather than a day-to-day event.',
    numerology:'Zero holds infinite potential. It is the empty circle, the seed before the tree, the breath before the word. Zero contains all numbers within it.',
    astrology:'Ruled by Uranus, planet of sudden insight, rebellion, and radical freedom. The Fool carries Uranian energy: unpredictable, electric, and unconcerned with convention.',
    foolsJourney:'This is the very first step. The Fool has not yet begun the journey and carries no map, no baggage, and no fear. Every card that follows is a lesson The Fool will encounter.',
    selfPerception:'You see yourself as unbounded. You believe anything is possible because you have not yet learned what is "impossible." There is a lightness to your identity that others may read as naivety or as courage.',
    worldOutlook:'The world appears as an open field. Logically, you recognize risk but choose not to let it dictate your movement. Emotionally, you feel a magnetic pull toward the unknown.',
    upright:{brief:'A leap into the unknown with trust that the ground will appear.',detail:'The Fool steps to the edge of a cliff with eyes raised skyward, a white rose of pure intention in hand. This is not recklessness but radical trust. You are being called to begin something without guarantees, to trust the process before you can see the outcome. The universe is offering a clean slate, a moment where the weight of past experience does not apply. This is the energy of the first breath, the blank page, the open road.',advice:'Take the leap. Do not wait for certainty because it will never arrive at this stage. Begin before you feel ready. The caution here is not to confuse innocence with ignorance. Pack lightly but do not forget to pack. Trust the journey, but watch where you place your feet.'},
    reversed:{brief:'Hesitation at the edge, or recklessness disguised as freedom.',detail:'Reversed, The Fool either freezes at the cliff edge or jumps without looking. The pure potential of the upright position becomes contaminated by fear on one side or carelessness on the other. You may be holding yourself back from a necessary beginning, or you may be rushing into something without any preparation, calling it spontaneity when it is actually avoidance of responsibility.',advice:'Ask yourself honestly: are you standing still because you are afraid, or because the timing is genuinely wrong? If you are leaping, check whether you are running toward something or away from something. Recklessness is not courage. Paralysis is not wisdom.'},
    scores:{spirit:10, m0:10}},

  { id:'m1', name:'The Magician', num:1, suit:'major',
    keywords:['willpower','manifestation','skill','resourcefulness'],
    symbol:{layers:['outerCircle','star5','infinity','rays','dot'],rayCount:8},
    colors:{primary:'#6b4aaa',secondary:'#9b7acc',accent:'#c8a45c'},
    deckPosition:'Card I, the first numbered card of the Major Arcana. The Magician is the first conscious act after The Fool takes the leap.',
    suitMeaning:'As a Major Arcana card, The Magician represents mastery of will and the bridge between spiritual intention and material reality.',
    numerology:'One is the number of initiative, individuality, and focused will. It is the single point from which all creation radiates.',
    astrology:'Ruled by Mercury, planet of communication, intellect, and skill. Mercury gives The Magician the ability to translate ideas into action through precise language and mental agility.',
    foolsJourney:'Having leaped, The Fool encounters the first teacher: the self as channel. The Magician shows that you already possess all four elements (the tools on his table) and need only focus your will to use them.',
    selfPerception:'You see yourself as capable and resourceful. You believe you can shape reality through focused intention and skill. There is a confidence in your identity that comes from knowing you have the tools.',
    worldOutlook:'The world appears as raw material waiting to be shaped. Logically, you see cause and effect clearly. Emotionally, you feel empowered, perhaps even invincible.',
    upright:{brief:'You have everything you need. Focus your will and create.',detail:'The Magician stands with one hand pointing to heaven and the other to earth, channeling divine energy into material form. Before him lie the four suit symbols: wand, cup, sword, and pentacle. This is the card of conscious creation, of knowing that you possess every resource required and choosing to use them with precision. You are not waiting for permission or better tools. The power is already flowing through you.',advice:'Act now with full confidence in your abilities. Channel your energy toward a single clear intention rather than scattering it across many. The challenge is maintaining focus when distractions arise. The caution is against manipulation: The Magician can become the con artist if skill is used without integrity.'},
    reversed:{brief:'Untapped potential or skill misused for deception.',detail:'Reversed, The Magician either cannot access his tools or uses them to deceive. The channel between intention and manifestation is blocked, distorted, or deliberately misused. You may be doubting your own competence, or you may be using your considerable talents to manipulate situations in ways that serve your ego rather than your purpose.',advice:'If you feel powerless, the block is internal, not external. Reconnect with your intention. If you are using your gifts to control or deceive, know that The Magician reversed always eventually gets caught. Realign skill with sincerity.'},
    scores:{spirit:10, m1:10}},

  { id:'m2', name:'The High Priestess', num:2, suit:'major',
    keywords:['intuition','mystery','inner knowledge','the unconscious'],
    symbol:{layers:['outerCircle','crescent','innerCircle','dottedRing','dot'],dots:9},
    colors:{primary:'#1a2a5e',secondary:'#3a5a8e',accent:'#a0b4d0'},
    deckPosition:'Card II. She sits between two pillars, guarding the threshold between the conscious and unconscious mind.',
    suitMeaning:'As a Major Arcana card, The High Priestess governs the deepest layers of knowing that exist beneath rational thought.',
    numerology:'Two is the number of duality, receptivity, and the tension between opposites. It is the space between action and stillness where wisdom gestates.',
    astrology:'Ruled by the Moon, governing cycles, intuition, the unconscious, and the hidden tides of emotion. The Moon reveals what the Sun cannot see.',
    foolsJourney:'After learning to act (The Magician), The Fool must learn to listen. The High Priestess teaches that not everything can be seized by will. Some knowledge arrives only in silence.',
    selfPerception:'You see yourself as someone who knows more than you can explain. Your identity is rooted in an inner life that others rarely glimpse. You trust the unseen.',
    worldOutlook:'The world has a hidden layer beneath its surface. Logically, you recognize that not everything is knowable through analysis. Emotionally, you feel the pull of mystery and the sacred feminine.',
    upright:{brief:'Be still. The answer you seek is already within you.',detail:'The High Priestess sits in silence between the pillars of Solomon, a scroll of hidden law on her lap. She does not speak because the knowledge she guards cannot be transmitted through words. This card appears when you are being called to stop seeking externally and turn inward. The answer is not in another book, another opinion, or another plan. It is in your body, your dreams, your unspoken knowing.',advice:'Trust what you feel even when you cannot prove it. Create space for stillness and receptivity. The challenge is patience, because intuitive knowledge often arrives on its own schedule. The caution is against sharing sacred insights prematurely: not every truth is meant for every audience.'},
    reversed:{brief:'Disconnection from intuition or secrets creating distance.',detail:'Reversed, The High Priestess has lost access to her inner voice, or she is withholding knowledge that should be shared. The veil between conscious and unconscious has thickened. You may be ignoring your intuition in favor of logic alone, or you may be keeping secrets that are isolating you from those you love.',advice:'If you cannot hear your intuition, you are living too loudly. Reduce external noise. If you are keeping secrets, ask whether the secrecy serves protection or avoidance. Reconnect with silence.'},
    scores:{spirit:10, m2:10}},

  { id:'m3', name:'The Empress', num:3, suit:'major',
    keywords:['abundance','nurturing','creativity','sensuality'],
    symbol:{layers:['outerCircle','hexagon','innerCircle','dottedRing','dotLarge'],dots:12},
    colors:{primary:'#2e6b3e',secondary:'#5a9b5a',accent:'#c8a45c'},
    deckPosition:'Card III. She is the fertile queen, seated in a field of golden wheat with a river flowing beside her.',
    suitMeaning:'As a Major Arcana card, The Empress embodies the creative force of nature and the principle of unconditional nurturing.',
    numerology:'Three is the number of creation, expression, and the first fruit of union. It is the child born from the meeting of two forces.',
    astrology:'Ruled by Venus, planet of love, beauty, pleasure, and the arts. Venus gives The Empress her magnetism, her sensuality, and her devotion to beauty.',
    foolsJourney:'The Fool learns that creation is not only an act of will (The Magician) or intuition (The High Priestess) but also of love. The Empress teaches nurturing, patience, and the body as a source of wisdom.',
    selfPerception:'You see yourself as someone who creates life, beauty, and comfort. Your identity is connected to your ability to nurture, whether that means people, projects, or environments.',
    worldOutlook:'The world is abundant when treated with care. Logically, you see growth as a natural process that requires tending. Emotionally, you feel deeply connected to the physical senses and to the people you love.',
    upright:{brief:'Abundance is flowing. Nurture what is growing.',detail:'The Empress reclines in a lush garden, surrounded by the evidence of her creative power. Everything she touches grows. This card appears when fertility, abundance, and creative energy are at their peak. You are being invited to receive pleasure, to create beauty, and to trust the organic unfolding of what you have planted. This is not a time for force but for nurturing.',advice:'Tend to what is already growing. Allow yourself pleasure without guilt. Create from a place of overflow rather than scarcity. The challenge is knowing when nurturing becomes smothering. The caution is against neglecting your own needs while feeding everyone else.'},
    reversed:{brief:'Creative block or neglect of what needs care.',detail:'Reversed, The Empress is cut off from her creative source. The garden is untended, the body is neglected, the heart is closed to pleasure. You may be experiencing creative drought, codependency, or a refusal to care for your physical wellbeing.',advice:'Ask what you have stopped nourishing. Your body, your art, your relationships? Return to the senses. Cook a real meal. Walk in nature. Pleasure is not optional. The caution is against martyrdom: you cannot give from an empty vessel.'},
    scores:{spirit:10, m3:10}},

  { id:'m4', name:'The Emperor', num:4, suit:'major',
    keywords:['authority','structure','stability','discipline'],
    symbol:{layers:['outerCircle','square','cross','rays','dotLarge'],rayCount:4},
    colors:{primary:'#8b2500',secondary:'#c04420',accent:'#c8a45c'},
    deckPosition:'Card IV. He sits on a stone throne carved with ram heads, mountains rising behind him. He is the established ruler.',
    suitMeaning:'As a Major Arcana card, The Emperor represents the principle of order, law, and the conscious structuring of reality.',
    numerology:'Four is the number of stability, foundations, and the material world. Four walls, four seasons, four elements. It is the number that makes things solid.',
    astrology:'Ruled by Aries, the first sign of the zodiac, representing initiative, leadership, and the warrior spirit. Mars, ruler of Aries, adds discipline and drive.',
    foolsJourney:'After experiencing unconditional nurturing (The Empress), The Fool encounters conditional structure. The Emperor teaches that love alone is not enough. Boundaries, rules, and accountability create the container in which growth can be sustained.',
    selfPerception:'You see yourself as a builder and protector. Your identity is tied to your ability to create order, provide security, and lead with authority.',
    worldOutlook:'The world requires structure to function. Logically, you see chaos as a problem to be organized. Emotionally, you feel most secure when boundaries are clear and expectations are defined.',
    upright:{brief:'Establish order. Build the structure that will hold your vision.',detail:'The Emperor surveys his domain from a position of earned authority. He has fought for this stability and maintains it through discipline, not tyranny. This card appears when you need to take command, set boundaries, create systems, or step into a leadership role. The situation calls for logic over emotion, structure over spontaneity.',advice:'Lead with clarity and consistency. Set boundaries that protect what matters. Build systems that will outlast your personal energy. The challenge is remaining compassionate within structure. The caution is against rigidity: the strongest structures flex in the wind.'},
    reversed:{brief:'Tyranny, rigidity, or abdication of responsibility.',detail:'Reversed, The Emperor becomes either a tyrant who uses authority to control rather than protect, or an absent ruler who avoids the responsibility of leadership entirely. Structure collapses into chaos or hardens into oppression.',advice:'If you are controlling, ask what you are afraid of losing. Real authority does not need to crush dissent. If you are avoiding leadership, ask what responsibility you are refusing. Someone needs you to step up.'},
    scores:{spirit:10, m4:10}},

  { id:'m5', name:'The Hierophant', num:5, suit:'major',
    keywords:['tradition','spiritual wisdom','conformity','mentorship'],
    symbol:{layers:['outerCircle','triUp','cross','dottedInner','dotLarge']},
    colors:{primary:'#5a3a1a',secondary:'#8a6a3a',accent:'#c8a45c'},
    deckPosition:'Card V. He sits between two pillars of a sacred institution, two acolytes kneeling before him. He is the bridge between the divine and the congregation.',
    suitMeaning:'As a Major Arcana card, The Hierophant represents established spiritual and cultural systems of meaning.',
    numerology:'Five is the number of challenge, change, and the human experience. It disrupts the stability of four, introducing questions that demand answers beyond the material.',
    astrology:'Ruled by Taurus, the sign of values, tradition, and the physical expression of the sacred. Taurus grounds spiritual teaching in embodied practice.',
    foolsJourney:'The Fool, having learned personal authority (The Emperor), now encounters collective wisdom. The Hierophant asks: what do the traditions and teachers who came before you have to offer?',
    selfPerception:'You see yourself as a student, a teacher, or both. Your identity is connected to a lineage of knowledge, whether religious, academic, or cultural.',
    worldOutlook:'The world is best understood through tested frameworks. Logically, you value systems that have survived the test of time. Emotionally, you find comfort in belonging to something larger than yourself.',
    upright:{brief:'Seek the wisdom of tradition. Learn from those who walked before you.',detail:'The Hierophant raises his hand in blessing, transmitting accumulated wisdom through established ritual and teaching. This card appears when you benefit from conventional paths: formal education, mentorship, spiritual practice within a tradition, or adherence to proven methods. Not every wheel needs reinventing.',advice:'Find a teacher, a tradition, or a community that holds knowledge you need. Study with humility. The challenge is discernment: knowing which traditions serve growth and which serve control. The caution is against blind obedience. Even the wisest teacher can be wrong.'},
    reversed:{brief:'Questioning dogma or breaking from tradition.',detail:'Reversed, The Hierophant represents rebellion against outdated structures, rejection of authority, or a personal spiritual path that diverges from the mainstream. You may be outgrowing a belief system or refusing guidance you actually need.',advice:'Examine whether you are rejecting tradition because it no longer serves you, or because you fear the vulnerability of being taught. Independence is valuable, but so is humility. Break rules consciously, not reactively.'},
    scores:{spirit:10, m5:10}},

  { id:'m6', name:'The Lovers', num:6, suit:'major',
    keywords:['union','choice','values alignment','sacred relationship'],
    symbol:{layers:['outerCircle','triUp','triDown','innerCircle','dot']},
    colors:{primary:'#a04060',secondary:'#d07090',accent:'#c8a45c'},
    deckPosition:'Card VI. An angel blesses two figures standing beneath the Tree of Knowledge and the Tree of Life. This is the card of conscious choice.',
    suitMeaning:'As a Major Arcana card, The Lovers transcends romantic love to represent the fundamental human act of choosing what you value.',
    numerology:'Six is the number of harmony, balance, and responsibility. It is the first "perfect number" in mathematics, equal to the sum of its divisors.',
    astrology:'Ruled by Gemini, the sign of duality, communication, and the integration of opposites. Gemini energy asks you to hold two truths simultaneously.',
    foolsJourney:'The Fool faces the first great choice. Having learned from institutions (The Hierophant), The Fool must now decide what aligns with personal truth. The Lovers is about choosing your own values.',
    selfPerception:'You see yourself through the mirror of relationship. Your identity is clarified by what and whom you choose, and by what you are willing to sacrifice.',
    worldOutlook:'The world is defined by the choices you make. Logically, you understand that every yes contains a no. Emotionally, you seek alignment between desire and values.',
    upright:{brief:'A choice that must align head and heart.',detail:'The Lovers depicts a moment of sacred choice. This is not simply about romantic love, although it often appears in that context. It is about any decision where your values are tested, where you must choose between the easy path and the true path, between what you want and what you need.',advice:'Choose from your deepest values, not from convenience or fear. If this involves a relationship, ensure it is built on genuine alignment rather than projection. The challenge is accepting that choosing one path means closing another. The caution is against making choices to please others at the expense of your own integrity.'},
    reversed:{brief:'Misalignment of values or avoidance of a necessary choice.',detail:'Reversed, The Lovers signals a disconnect between what you say you value and how you actually live. There may be a relationship built on fantasy rather than reality, or a decision you are avoiding because neither option is comfortable.',advice:'Stop postponing the choice. Discomfort now is preferable to prolonged misalignment. If a relationship feels wrong, trust that feeling. The caution is against self-deception: wanting something to work is not the same as it working.'},
    scores:{spirit:10, m6:10}},

  { id:'m7', name:'The Chariot', num:7, suit:'major',
    keywords:['determination','victory','willpower','forward momentum'],
    symbol:{layers:['outerCircle','diamond','rays','cross','dot'],rayCount:8},
    colors:{primary:'#2a4a7a',secondary:'#4a7aba',accent:'#c8a45c'},
    deckPosition:'Card VII. A warrior stands in a chariot pulled by two sphinxes, one black and one white, requiring mastery of opposing forces to move forward.',
    suitMeaning:'As a Major Arcana card, The Chariot represents the triumph of focused will over internal and external obstacles.',
    numerology:'Seven is the number of spiritual seeking, inner work, and the victory that comes from alignment rather than brute force.',
    astrology:'Ruled by Cancer, the sign of emotional intelligence, protection, and the hard shell that guards a soft interior. Cancer reminds us that true strength includes vulnerability.',
    foolsJourney:'Having made a conscious choice (The Lovers), The Fool must now move forward with determination. The Chariot teaches that willpower, not circumstances, determines direction.',
    selfPerception:'You see yourself as someone who overcomes. Your identity is forged in motion, in conquest, in the refusal to be stopped by contradiction or resistance.',
    worldOutlook:'The world is a terrain to be navigated with skill and determination. Logically, you see obstacles as puzzles to solve. Emotionally, you feel the thrill of momentum and the fear of losing control.',
    upright:{brief:'Harness opposing forces and move forward with focused will.',detail:'The Chariot commands two beasts that pull in different directions. Victory comes not from eliminating conflict but from holding tension and steering through it. You are being called to take decisive action despite uncertainty, to move forward even when parts of you resist.',advice:'Commit to your direction and do not waver. Channel contradictions into momentum rather than allowing them to paralyze you. The challenge is sustaining willpower over time without burning out. The caution is against confusing stubbornness with determination.'},
    reversed:{brief:'Loss of direction or aggression without purpose.',detail:'Reversed, The Chariot has lost its steering. The opposing forces are pulling apart rather than being harnessed. You may be pursuing a goal through sheer force when the direction itself is wrong, or you may have lost your sense of purpose entirely.',advice:'Stop and reassess your direction before pushing harder. More force applied in the wrong direction only takes you further from where you need to be. The caution is against road rage: anger at obstacles may be masking fear of the destination.'},
    scores:{spirit:10, m7:10}},

  { id:'m8', name:'Strength', num:8, suit:'major',
    keywords:['inner strength','courage','patience','gentle power'],
    symbol:{layers:['outerCircle','infinity','innerCircle','rays','dot'],rayCount:6},
    colors:{primary:'#b8860b',secondary:'#daa520',accent:'#f5e6c8'},
    deckPosition:'Card VIII. A woman gently closes the jaws of a lion, not through force but through calm compassion. The infinity symbol floats above her head.',
    suitMeaning:'As a Major Arcana card, Strength represents the quiet power that comes from mastering the self rather than dominating others.',
    numerology:'Eight is the number of balance, karma, and infinite cycles. Turned on its side, eight becomes the lemniscate, the infinity symbol of eternal flow.',
    astrology:'Ruled by Leo, the sign of courage, heart, and creative self-expression. Leo reminds us that true strength is generous, warm, and unafraid of vulnerability.',
    foolsJourney:'After external victory (The Chariot), The Fool discovers that the greatest battle is internal. Strength teaches that raw emotion, like the lion, is not the enemy but a force to be befriended.',
    selfPerception:'You see yourself as quietly resilient. Your identity is defined not by what you can conquer but by what you can endure with grace and what you can tame with compassion.',
    worldOutlook:'The world responds to gentleness more than aggression. Logically, you know that force creates resistance. Emotionally, you feel the deep well of patience and courage within you.',
    upright:{brief:'True power is gentle. Meet your inner lion with compassion.',detail:'Strength depicts mastery through softness. The woman does not wrestle the lion into submission. She closes its mouth with a touch, calming it through the certainty of her presence. This card appears when you need endurance rather than explosiveness, patience rather than speed, compassion rather than judgment, especially toward yourself.',advice:'Lead with your heart, not your ego. Meet fear, anger, or desire with gentle firmness rather than suppression or indulgence. The challenge is maintaining patience when progress feels slow. The caution is against mistaking passivity for patience. Gentle power still acts.'},
    reversed:{brief:'Self-doubt, raw insecurity, or misuse of gentle influence.',detail:'Reversed, Strength loses confidence. The lion is either running wild (emotions ungoverned) or the woman has walked away (giving up on herself). There may be deep self-doubt masquerading as humility, or an inability to stand firm when it matters.',advice:'If the lion is loose, it is because you have abandoned the compassionate discipline that keeps it calm. Return to self-care, boundaries, and honest self-assessment. If you have given up, remember that endurance is not about never falling. It is about rising again.'},
    scores:{spirit:10, m8:10}},

  { id:'m9', name:'The Hermit', num:9, suit:'major',
    keywords:['solitude','soul-searching','inner guidance','wisdom'],
    symbol:{layers:['outerCircle','star6','dottedInner','rays','dot'],rayCount:6},
    colors:{primary:'#3a3a5a',secondary:'#5a5a8a',accent:'#e0c97a'},
    deckPosition:'Card IX. An old sage stands alone on a mountain peak, holding a lantern containing a six-pointed star. He lights the way for those who follow.',
    suitMeaning:'As a Major Arcana card, The Hermit represents the universal need for withdrawal from the world in order to find truth within.',
    numerology:'Nine is the number of completion of a cycle, wisdom earned through experience, and the solitary path of the seeker who has seen enough to know what matters.',
    astrology:'Ruled by Virgo, the sign of discernment, service, and the sacred in the mundane. Virgo energy refines, purifies, and seeks the essential.',
    foolsJourney:'Having developed inner strength (Strength), The Fool now withdraws from the world to integrate everything learned so far. The Hermit teaches that some truths can only be found in solitude.',
    selfPerception:'You see yourself as a seeker. Your identity is defined by the depth of your questions rather than the breadth of your social life. You carry a light that others notice even when you try to hide.',
    worldOutlook:'The world is noisy and often distracting from what matters. Logically, you understand that clarity requires removing interference. Emotionally, you oscillate between the peace of solitude and the ache of isolation.',
    upright:{brief:'Withdraw. The truth you seek requires silence to hear.',detail:'The Hermit has climbed above the clouds to see clearly. This is not escapism but purposeful withdrawal, a temporary retreat from the noise of the world in order to reconnect with inner truth. The lantern in his hand is not for himself; he already sees. It is for those who will follow when he returns.',advice:'Take time alone. Not forever, but long enough to hear your own voice beneath the opinions of others. Seek a mentor if one appears, or become the mentor you needed. The challenge is knowing when solitude becomes hiding. The caution is against spiritual bypassing: using "inner work" to avoid the messy reality of human connection.'},
    reversed:{brief:'Isolation, withdrawal from life, or refusing to share wisdom.',detail:'Reversed, The Hermit has stayed on the mountain too long. Solitude has become isolation. The lantern is hooded, the wisdom unshared. You may be avoiding life under the guise of introspection, or you may be surrounded by people yet feeling utterly alone.',advice:'Come down from the mountain. Wisdom hoarded is wisdom wasted. If isolation is involuntary, recognize that reaching out is not weakness. The caution is against using solitude as a shield against vulnerability.'},
    scores:{spirit:10, m9:10}},

  { id:'m10', name:'Wheel of Fortune', num:10, suit:'major',
    keywords:['cycles','fate','turning point','destiny'],
    symbol:{layers:['outerCircle','innerCircle','cross','dottedRing','star6','dot'],dots:12},
    colors:{primary:'#4a2d7a',secondary:'#6b4aaa',accent:'#c8a45c'},
    deckPosition:'Card X. A great wheel turns in the sky, surrounded by the four fixed signs of the zodiac. Figures rise and fall on its rim.',
    suitMeaning:'As a Major Arcana card, The Wheel of Fortune represents the cosmic forces of change that operate beyond individual will.',
    numerology:'Ten is the number of completion and return to one (1+0=1). It marks the end of one cycle and the beginning of the next, a spiral rather than a circle.',
    astrology:'Ruled by Jupiter, the planet of expansion, luck, philosophy, and the larger patterns of meaning. Jupiter sees the long arc of the story.',
    foolsJourney:'The Fool, having found inner wisdom (The Hermit), now confronts the reality that not everything is within personal control. The Wheel teaches that life moves in cycles and that the only constant is change itself.',
    selfPerception:'You see yourself as part of something larger. Your identity shifts between feeling blessed and feeling buffeted. You are learning that you are not the wheel but the awareness watching it turn.',
    worldOutlook:'The world moves in cycles that no individual controls. Logically, you recognize patterns of rise and fall. Emotionally, you feel the vertigo of change and the relief of knowing that nothing, good or bad, lasts forever.',
    upright:{brief:'The wheel is turning. A shift in fortune is arriving.',detail:'The Wheel of Fortune marks a turning point driven by forces larger than your personal will. Luck, karma, and the natural rhythm of cycles are at work. If you have been struggling, relief is coming. If you have been coasting, change is approaching. This card reminds you that life is never static.',advice:'Ride the turn rather than resisting it. Recognize what is ending and what is beginning. The challenge is accepting that you did not cause this shift and cannot fully control it. The caution is against arrogance in good times and despair in hard times: the wheel keeps turning.'},
    reversed:{brief:'Resistance to change or a difficult turn in the cycle.',detail:'Reversed, The Wheel indicates resistance to an inevitable change, or a downturn that feels undeserved. The cycle is still moving, but you are clinging to the previous position. Bad luck, delays, and the feeling of being stuck often accompany this reversal.',advice:'Stop fighting the current. The harder you cling to what was, the more painful the transition becomes. Look for the lesson in the downturn. The caution is against blaming fate for consequences that may include your own choices.'},
    scores:{spirit:10, m10:10}}
];
