// Pentacles - Earth element (14 cards)
const SUIT = 'The Suit of Pentacles belongs to the element of Earth, governing material reality, work, finances, health, and the sacred craft of building something that lasts.';
const EL = 'pentacles';

export const PENTACLES = [
  { id:'p1', name:'Ace of Pentacles', num:1, suit:EL, keywords:['opportunity','prosperity','new venture','material beginning'],
    symbol:{layers:['outerCircle','hexagon','dottedRing','dot'],dots:5},
    colors:{primary:'#3a6a2a',secondary:'#5a8a4a',accent:'#8aba7a'},
    deckPosition:'The root energy of the Pentacles suit. The pure seed of material and physical potential.',
    suitMeaning:SUIT, numerology:'One is pure potential. In Pentacles, it is the first opportunity for material growth, a new financial or physical beginning.',
    astrology:'Associated with the earth signs (Taurus, Virgo, Capricorn) in their most fertile, receptive state.',
    foolsJourney:'A material opportunity appears. The seed of prosperity is offered and requires planting and tending.',
    selfPerception:'You see yourself as someone being offered a practical opportunity. Your identity is ready to grow into something solid.',
    worldOutlook:'The world is offering a tangible chance. Logically, the opportunity is real. Emotionally, you feel grounded and hopeful.',
    upright:{brief:'A new material opportunity arrives. Plant the seed.',detail:'The Ace of Pentacles shows a hand emerging from clouds offering a golden coin above a garden gate. This is the beginning of a new financial venture, career opportunity, health practice, or material investment. The seed is real and fertile.',advice:'Accept the opportunity and commit to tending it. Material growth takes time and consistent effort. The challenge is patience: this seed will not bear fruit overnight. The caution is against greed. One solid opportunity cultivated well outperforms ten scattered bets.'},
    reversed:{brief:'Missed opportunity or poor financial planning.',detail:'Reversed, the coin falls or is not picked up. A material opportunity is being missed, or the planning behind a new venture is inadequate.',advice:'If you missed it, another will come. If your planning is weak, strengthen it before investing. Build the foundation before the walls.'},
    scores:{fire:0,water:0,air:0,earth:5,spirit:2,beginning:5,growth:2,mastery:0,completion:0}},

  { id:'p2', name:'Two of Pentacles', num:2, suit:EL, keywords:['balance','adaptability','juggling','flexibility'],
    symbol:{layers:['outerCircle','infinity','dottedRing','dot'],dots:2},
    colors:{primary:'#4a7a3a',secondary:'#6a9a5a',accent:'#a0c090'},
    deckPosition:'The second stage: material life requires balancing multiple demands.',
    suitMeaning:SUIT, numerology:'Two is duality. In Pentacles, it is the juggling act of managing competing material demands.',
    astrology:'Jupiter in Capricorn. Expansive ambition constrained by practical limitations.',
    foolsJourney:'The Fool juggles two coins in an infinity loop. Life demands flexibility and the ability to handle multiple responsibilities.',
    selfPerception:'You see yourself as someone managing a lot. Your identity is tied to your ability to keep all the plates spinning.',
    worldOutlook:'The world demands multitasking and flexibility. Logically, you see the need for balance. Emotionally, the juggling is exhausting but manageable.',
    upright:{brief:'Juggle with grace. Balance competing demands through flexibility.',detail:'The Two of Pentacles shows a figure dancing while juggling two coins connected by an infinity loop. Ships ride choppy waves behind him. Life is demanding that you balance work and play, income and expenses, or multiple responsibilities.',advice:'Stay flexible. Rigid plans will break under this kind of pressure. The challenge is maintaining equilibrium without dropping anything critical. The caution is against perpetual juggling: if balance never arrives, something needs to be set down.'},
    reversed:{brief:'Overwhelm from too many commitments or financial imbalance.',detail:'Reversed, the juggling fails. Coins drop. You are overcommitted, financially strained, or unable to maintain the balance.',advice:'Something must be released. You cannot juggle indefinitely. Prioritize ruthlessly and let go of the least essential obligation.'},
    scores:{fire:0,water:0,air:1,earth:4,spirit:0,beginning:1,growth:4,mastery:1,completion:0}},

  { id:'p3', name:'Three of Pentacles', num:3, suit:EL, keywords:['teamwork','skill','craftsmanship','collaboration'],
    symbol:{layers:['outerCircle','triangle','dottedInner','hexagon','dot']},
    colors:{primary:'#5a7a4a',secondary:'#7a9a6a',accent:'#a0ba90'},
    deckPosition:'The third stage: individual skill combines with collaboration to produce quality work.',
    suitMeaning:SUIT, numerology:'Three is expression and growth. In Pentacles, it is the moment when craft meets collaboration.',
    astrology:'Mars in Capricorn. Disciplined ambition channeled into skilled workmanship.',
    foolsJourney:'The Fool discovers that great work requires both personal skill and the willingness to collaborate with others.',
    selfPerception:'You see yourself as a skilled contributor. Your identity is connected to the quality of your work and your ability to work with others.',
    worldOutlook:'The world values competence and teamwork. Logically, you see that the best results come from skilled collaboration.',
    upright:{brief:'Your skills are recognized. Collaborate to create something excellent.',detail:'The Three of Pentacles shows an artisan working in a cathedral while two figures review the plans together. This is the card of craftsmanship, teamwork, and the recognition of skilled work.',advice:'Invest in your craft. Collaborate with people whose skills complement yours. The challenge is ego: can you accept feedback and share credit? The caution is against working alone when collaboration would produce something better.'},
    reversed:{brief:'Poor teamwork, sloppy work, or unrecognized effort.',detail:'Reversed, the collaboration is dysfunctional or the work quality is slipping. Skills are not being valued or standards have dropped.',advice:'If teamwork is failing, address the communication gap. If your work is unrecognized, ensure the quality justifies the expectation.'},
    scores:{fire:0,water:0,air:1,earth:5,spirit:0,beginning:1,growth:4,mastery:2,completion:0}},

  { id:'p4', name:'Four of Pentacles', num:4, suit:EL, keywords:['security','possessiveness','conservation','control'],
    symbol:{layers:['outerCircle','square','dottedRing','crossSmall','dot']},
    colors:{primary:'#4a5a2a',secondary:'#6a7a4a',accent:'#8a9a6a'},
    deckPosition:'The fourth stage: material stability arrives, but the grip tightens.',
    suitMeaning:SUIT, numerology:'Four is stability. In Pentacles, stability can become rigidity when the fear of loss overwhelms the joy of having.',
    astrology:'Sun in Capricorn. The conservative instinct to protect what has been earned.',
    foolsJourney:'The Fool clutches a coin to the chest, two under the feet, one on the head. Security feels fragile and demands constant vigilance.',
    selfPerception:'You see yourself as the guardian of what you have earned. Your identity is tied to your material security.',
    worldOutlook:'The world is a threatening place that will take from you if you let your guard down. Logically, caution is justified. Emotionally, the grip is exhausting.',
    upright:{brief:'You are holding on tightly. Is it security or fear?',detail:'The Four of Pentacles shows a figure clutching coins with hands, feet, and crown. He has achieved stability but his grip is so tight he cannot move, embrace, or receive. This is the card of financial conservatism taken to the point of paralysis.',advice:'Examine what you are protecting and at what cost. Some saving is wise; hoarding is a prison. The challenge is loosening the grip without losing what matters. The caution is against letting fear of poverty drive you to an impoverished life.'},
    reversed:{brief:'Releasing control or financial instability.',detail:'Reversed, the grip loosens. You are either generously letting go of what you have been hoarding, or financial security is slipping through your fingers.',advice:'If releasing willingly, well done. If losing control, rebuild from what remains rather than grasping at what is gone.'},
    scores:{fire:0,water:0,air:0,earth:5,spirit:0,beginning:0,growth:1,mastery:4,completion:3}},

  { id:'p5', name:'Five of Pentacles', num:5, suit:EL, keywords:['hardship','poverty','isolation','struggle'],
    symbol:{layers:['outerCircle','dottedInner','triDown','crossSmall'],rotation:180},
    colors:{primary:'#2a3a2a',secondary:'#4a5a4a',accent:'#6a7a6a'},
    deckPosition:'The fifth stage: material disruption. Loss, hardship, and the feeling of being left out in the cold.',
    suitMeaning:SUIT, numerology:'Five is disruption. In Pentacles, it is financial hardship, health crisis, or the loss of material security.',
    astrology:'Mercury in Taurus. Practical communication about difficult material realities.',
    foolsJourney:'The Fool walks barefoot through snow, passing a lit church window. Help is available, but the Fool may be too proud or too defeated to ask.',
    selfPerception:'You see yourself as excluded from the warmth and security others enjoy. Your identity feels diminished by lack.',
    worldOutlook:'The world is cold and exclusive. Logically, you know help exists somewhere. Emotionally, shame prevents you from asking.',
    upright:{brief:'Hardship is real, but help is closer than you think.',detail:'The Five of Pentacles shows two impoverished figures passing a church with a glowing stained-glass window. They are so focused on their suffering that they do not look up to see the sanctuary nearby. This is the card of financial hardship, health challenges, or feeling excluded.',advice:'Look up. Help is available, but you must be willing to receive it. The challenge is asking for help when pride says you should manage alone. The caution is against wearing hardship as an identity. Suffering is a season, not a sentence.'},
    reversed:{brief:'Recovery from hardship or finding help.',detail:'Reversed, you look up and notice the lit window. Recovery begins, or help arrives from an unexpected source.',advice:'Accept the help. You have earned it by surviving the cold. Let others warm you.'},
    scores:{fire:0,water:1,air:0,earth:4,spirit:1,beginning:0,growth:2,mastery:0,completion:4}},

  { id:'p6', name:'Six of Pentacles', num:6, suit:EL, keywords:['generosity','charity','exchange','balance of giving'],
    symbol:{layers:['outerCircle','hexagon','dottedRing','innerCircle','dot'],dots:6},
    colors:{primary:'#4a8a4a',secondary:'#6aaa6a',accent:'#a0caa0'},
    deckPosition:'The sixth stage: balance is restored through the exchange of resources.',
    suitMeaning:SUIT, numerology:'Six restores harmony. In Pentacles, it is the balance of giving and receiving.',
    astrology:'Moon in Taurus. Emotional security expressed through material generosity.',
    foolsJourney:'The Fool learns that material resources flow best when they are shared. Giving and receiving are part of the same cycle.',
    selfPerception:'You see yourself as either a giver or a receiver. Your identity is shaped by your relationship with generosity.',
    worldOutlook:'The world functions through exchange. Logically, you see the value of fair distribution. Emotionally, you feel the warmth of generosity.',
    upright:{brief:'Give generously or receive graciously. Both require dignity.',detail:'The Six of Pentacles shows a wealthy figure distributing coins to two kneeling people, scales in his other hand. This is the card of charity, mentorship, and the balance of giving and receiving.',advice:'If you have abundance, share it with integrity, not as a power play. If you are receiving, accept without shame. The challenge is maintaining equality in the exchange. The caution is against using generosity to control.'},
    reversed:{brief:'Strings-attached generosity or imbalanced exchange.',detail:'Reversed, the giving comes with conditions, or the exchange is exploitative.',advice:'If generosity has strings, it is not generosity but leverage. If you are being exploited, name the imbalance.'},
    scores:{fire:0,water:1,air:0,earth:4,spirit:1,beginning:0,growth:3,mastery:2,completion:1}},

  { id:'p7', name:'Seven of Pentacles', num:7, suit:EL, keywords:['patience','assessment','long-term investment','waiting'],
    symbol:{layers:['outerCircle','dottedRing','innerCircle','hexagon','dot'],dots:7},
    colors:{primary:'#3a5a2a',secondary:'#5a7a4a',accent:'#8a9a7a'},
    deckPosition:'The seventh stage: the moment of pausing to assess what has been planted and whether it is growing well.',
    suitMeaning:SUIT, numerology:'Seven is assessment and patience. In Pentacles, it is the farmer leaning on his hoe, studying the crop.',
    astrology:'Saturn in Taurus. The discipline of long-term investment and patient cultivation.',
    foolsJourney:'The Fool pauses to evaluate. Not everything planted will bear fruit. Some investments need more time; some need to be abandoned.',
    selfPerception:'You see yourself as someone between effort and result. Your identity includes the patience of the long game.',
    worldOutlook:'The world rewards patience, but not endlessly. Logically, you are assessing return on investment. Emotionally, you are tired of waiting.',
    upright:{brief:'Pause and assess. Is this investment still worth your effort?',detail:'The Seven of Pentacles shows a figure leaning on a gardening tool, studying seven coins growing on a vine. The harvest is not yet ready. This card asks whether you are willing to keep tending, or whether the crop should be abandoned for a more promising field.',advice:'Evaluate honestly. Not every investment pays off. The challenge is distinguishing patience from stubbornness. The caution is against abandoning something that simply needs more time.'},
    reversed:{brief:'Impatience with slow results or poor return on investment.',detail:'Reversed, patience has run out. Results are not materializing, or the investment was fundamentally flawed.',advice:'If the crop is truly failing, pull it up. If you are simply impatient, adjust your timeline, not your commitment.'},
    scores:{fire:0,water:0,air:1,earth:5,spirit:0,beginning:0,growth:2,mastery:4,completion:1}},

  { id:'p8', name:'Eight of Pentacles', num:8, suit:EL, keywords:['diligence','mastery','skill building','dedication'],
    symbol:{layers:['outerCircle','hexagon','dottedInner','rays','dot'],rayCount:8},
    colors:{primary:'#5a7a4a',secondary:'#7a9a6a',accent:'#a0ba90'},
    deckPosition:'The eighth stage: mastery through devoted repetition and skill refinement.',
    suitMeaning:SUIT, numerology:'Eight is mastery and power. In Pentacles, it is the devoted craftsman perfecting his art through practice.',
    astrology:'Sun in Virgo. The meticulous attention to detail that produces excellence.',
    foolsJourney:'The Fool commits to the craft. Not through talent alone but through the discipline of daily practice.',
    selfPerception:'You see yourself as an apprentice becoming a master. Your identity is defined by your dedication to quality.',
    worldOutlook:'The world rewards skilled, dedicated effort. Logically, you see the path from novice to master. Emotionally, you find satisfaction in the work itself.',
    upright:{brief:'Commit to the craft. Mastery comes through dedicated practice.',detail:'The Eight of Pentacles shows an artisan at his bench, carefully carving coins one by one. He is fully absorbed in the work. This is the card of skill development, apprenticeship, and the love of the craft itself.',advice:'Practice. Study. Refine. The work itself is the reward at this stage. The challenge is avoiding shortcuts. The caution is against perfectionism: "good enough" is sometimes the enemy of "finished."'},
    reversed:{brief:'Sloppy work, lack of dedication, or meaningless labor.',detail:'Reversed, the quality drops. Work is being done carelessly, or the labor has become meaningless repetition without growth.',advice:'If your work lacks quality, reconnect with the purpose behind it. If the work feels pointless, it may be time to find a new craft.'},
    scores:{fire:0,water:0,air:1,earth:5,spirit:0,beginning:0,growth:3,mastery:4,completion:1}},

  { id:'p9', name:'Nine of Pentacles', num:9, suit:EL, keywords:['abundance','self-sufficiency','luxury','independence'],
    symbol:{layers:['outerCircle','hexagon','dottedRing','innerCircle','dotLarge'],dots:9},
    colors:{primary:'#4a7a2a',secondary:'#6a9a4a',accent:'#a0c080'},
    deckPosition:'The ninth stage: material mastery produces independence, abundance, and refined enjoyment.',
    suitMeaning:SUIT, numerology:'Nine is near completion. In Pentacles, it is the abundance earned through discipline and wise investment.',
    astrology:'Venus in Virgo. The marriage of beauty and practicality in a life well-built.',
    foolsJourney:'The Fool stands in a beautiful garden, surrounded by the fruits of sustained effort. Independence is the reward.',
    selfPerception:'You see yourself as self-sufficient and accomplished. Your identity includes the quiet pride of having built this life with your own hands.',
    worldOutlook:'The world is abundant for those who invest wisely and work diligently. You are living proof.',
    upright:{brief:'Enjoy the abundance you have earned. You built this.',detail:'The Nine of Pentacles shows a well-dressed woman standing in a vineyard, a falcon on her wrist. She is financially independent, surrounded by luxury, and at peace with her accomplishments.',advice:'Savor what you have created. You earned this. The challenge is allowing yourself pleasure without guilt. The caution is against isolation: abundance without sharing can become a gilded cage.'},
    reversed:{brief:'Financial setback or dependence on others.',detail:'Reversed, the independence is threatened. Financial setbacks, over-reliance on someone else, or the realization that material abundance alone does not equal fulfillment.',advice:'If security is shaken, draw on the skills that built it in the first place. If the abundance feels hollow, look for what money cannot buy.'},
    scores:{fire:0,water:0,air:0,earth:5,spirit:1,beginning:0,growth:0,mastery:4,completion:4}},

  { id:'p10', name:'Ten of Pentacles', num:10, suit:EL, keywords:['legacy','wealth','family','long-term success'],
    symbol:{layers:['outerCircle','hexagon','dottedRing','innerCircle','cross','dotLarge'],dots:10},
    colors:{primary:'#3a5a2a',secondary:'#5a7a4a',accent:'#8aaa7a'},
    deckPosition:'The tenth and final numbered stage: the material journey reaches its fullest expression in legacy and generational wealth.',
    suitMeaning:SUIT, numerology:'Ten completes the cycle. In Pentacles, it is the wealth that extends beyond the individual to sustain a family, community, or legacy.',
    astrology:'Mercury in Virgo. The practical wisdom that builds systems outlasting their creator.',
    foolsJourney:'The material journey is complete. What was built endures and benefits those who come after.',
    selfPerception:'You see yourself as part of a lineage. Your identity includes what you will leave behind for others.',
    worldOutlook:'The world is shaped by those who build for the long term. Logically, you see the value of legacy. Emotionally, you feel the weight and pride of responsibility.',
    upright:{brief:'Legacy and lasting wealth. What you built will outlive you.',detail:'The Ten of Pentacles shows an elder in an archway, surrounded by family, dogs, and the symbols of generational wealth. This is the card of dynasty, inheritance, and the material stability that supports an entire family or community.',advice:'Think beyond yourself. Build for the next generation. The challenge is sharing control of what you built. The caution is against letting family wealth create family dysfunction. Money without values is a burden, not a gift.'},
    reversed:{brief:'Family financial disputes or legacy in jeopardy.',detail:'Reversed, the legacy is threatened by poor planning, family conflict, or values that were not transmitted alongside the wealth.',advice:'If the legacy is at risk, address the human issues before the financial ones. No amount of money can substitute for a shared vision.'},
    scores:{fire:0,water:1,air:0,earth:5,spirit:0,beginning:0,growth:0,mastery:3,completion:5}},

  { id:'p11', name:'Page of Pentacles', num:11, suit:EL, keywords:['ambition','studiousness','new skill','practical beginning'],
    symbol:{layers:['outerCircle','hexagon','starSmall','dot']},
    colors:{primary:'#4a6a3a',secondary:'#6a8a5a',accent:'#8aaa7a'},
    deckPosition:'The Page is the student of earth: diligent, curious about practical matters, and ready to learn.',
    suitMeaning:SUIT, numerology:'Pages represent a new relationship with their element. In Pentacles, it is the student discovering the satisfaction of skilled work.',
    astrology:'Earth of Earth. The most grounded energy in the deck: focused, practical, and methodical.',
    foolsJourney:'A new practical venture begins. The student approaches material reality with fresh eyes and quiet determination.',
    selfPerception:'You see yourself as someone at the beginning of a practical journey. Your identity is open to learning and willing to start small.',
    worldOutlook:'The world rewards those who start small and build patiently.',
    upright:{brief:'A new skill or practical opportunity. Begin with dedication.',detail:'The Page of Pentacles stands in a green field, gazing intently at a golden coin hovering above his hands. He is the eternal student of practical arts, the person who says "teach me" without shame.',advice:'Begin the course. Start the practice. Learn the skill. The challenge is maintaining interest through the unglamorous early stages. The caution is against studying forever without applying.'},
    reversed:{brief:'Lack of follow-through or unrealistic material goals.',detail:'Reversed, the Page dreams of material success without doing the work, or abandons practical training when it becomes tedious.',advice:'Dreams without labor are fantasies. Start smaller if the goal feels overwhelming, but start.'},
    scores:{fire:0,water:0,air:1,earth:4,spirit:1,beginning:5,growth:2,mastery:0,completion:0}},

  { id:'p12', name:'Knight of Pentacles', num:12, suit:EL, keywords:['reliability','methodical','persistence','routine'],
    symbol:{layers:['outerCircle','hexagon','dottedInner','diamond','dot']},
    colors:{primary:'#3a5a2a',secondary:'#5a7a4a',accent:'#7a9a6a'},
    deckPosition:'The Knight is earth in motion, but unlike other knights, he moves slowly and deliberately.',
    suitMeaning:SUIT, numerology:'Knights represent active pursuit. In Pentacles, it is the steady, persistent work that outperforms dramatic bursts.',
    astrology:'Air of Earth. The practical thinker who plans methodically and executes patiently.',
    foolsJourney:'The Fool commits to the long road. Not flashy, not fast, but absolutely reliable.',
    selfPerception:'You see yourself as dependable and thorough. Your identity is defined by consistency rather than brilliance.',
    worldOutlook:'The world rewards persistence. Logically, you see that the tortoise beats the hare. Emotionally, you find peace in routine.',
    upright:{brief:'Slow and steady. Your persistence is your greatest asset.',detail:'The Knight of Pentacles sits on a heavy workhorse, surveying a plowed field. He is the most reliable figure in the deck, the one who shows up every day, does the work, and never quits.',advice:'Keep going. Your pace may not be exciting, but it is effective. The challenge is not becoming so routine-bound that you miss opportunities for growth. The caution is against mistaking stubbornness for dedication.'},
    reversed:{brief:'Stagnation, laziness, or work without purpose.',detail:'Reversed, the Knight stops moving entirely, or his persistence becomes meaningless repetition.',advice:'If stuck, change one small thing. If the work feels pointless, reconnect with the purpose behind the routine.'},
    scores:{fire:0,water:0,air:0,earth:5,spirit:0,beginning:0,growth:4,mastery:3,completion:1}},

  { id:'p13', name:'Queen of Pentacles', num:13, suit:EL, keywords:['nurturing abundance','practical wisdom','generosity','earthy warmth'],
    symbol:{layers:['outerCircle','hexagon','innerCircle','dottedRing','dotLarge']},
    colors:{primary:'#4a7a3a',secondary:'#6a9a5a',accent:'#a0c090'},
    deckPosition:'The Queen has mastered earth from within. She creates abundance through nurturing and practical wisdom.',
    suitMeaning:SUIT, numerology:'Queens represent internal mastery. In Pentacles, it is the ability to create material comfort and security through wisdom and care.',
    astrology:'Water of Earth. Emotional nurturing expressed through practical means.',
    foolsJourney:'Material mastery becomes an expression of love. The Queen does not just build; she creates environments where life flourishes.',
    selfPerception:'You see yourself as a provider and nurturer. Your identity includes the ability to make any space feel like home.',
    worldOutlook:'The world needs people who create abundance and share it. You see material care as an expression of love.',
    upright:{brief:'Create abundance and share it. Your practical wisdom nurtures all.',detail:'The Queen of Pentacles sits in a flowering garden, a golden coin on her lap, a rabbit at her feet. She is the embodiment of practical abundance: the person who creates a home, a garden, a business that nurtures everyone it touches.',advice:'Tend to the practical needs of those you love. Your ability to create material comfort is a gift. The challenge is caring for yourself as well as you care for others. The caution is against reducing your identity to your productivity.'},
    reversed:{brief:'Neglecting practical needs or over-focus on material comfort.',detail:'Reversed, the Queen either neglects the practical foundations or becomes so focused on material security that she forgets what it was for.',advice:'If you are neglecting basics, tend to them. If you are hoarding comfort, remember that a garden is meant to be enjoyed, not guarded.'},
    scores:{fire:0,water:1,air:0,earth:5,spirit:1,beginning:0,growth:2,mastery:5,completion:1}},

  { id:'p14', name:'King of Pentacles', num:14, suit:EL, keywords:['wealth','business acumen','reliability','material mastery'],
    symbol:{layers:['outerCircle','hexagon','cross','rays','innerCircle','dotLarge'],rayCount:4},
    colors:{primary:'#2a4a1a',secondary:'#4a6a3a',accent:'#6a8a5a'},
    deckPosition:'The King is the external master of earth: the builder of empires, the steward of wealth, the patron of lasting institutions.',
    suitMeaning:SUIT, numerology:'Kings represent external mastery. In Pentacles, it is the authority figure who has built lasting material success and manages it wisely.',
    astrology:'Fire of Earth. The driving ambition that builds material empires with patience and strategy.',
    foolsJourney:'Earth has been fully mastered. The King does not just accumulate; he stewards, invests, and builds for generations.',
    selfPerception:'You see yourself as a builder and steward. Your identity is tied to what you have created and the responsibility of maintaining it.',
    worldOutlook:'The world is built by those with the patience and skill to create lasting value. You see material success as a craft, not a windfall.',
    upright:{brief:'Material mastery. You have built something that endures.',detail:'The King of Pentacles sits on a throne adorned with bulls, his robes decorated with grapevines, a golden coin in his hand. He is the most materially successful figure in the deck, but his success comes from patience, skill, and wise stewardship, not from greed.',advice:'Manage what you have built with wisdom and generosity. Your material success is a platform for positive impact. The challenge is not becoming defined by your wealth. The caution is against complacency: empires require maintenance.'},
    reversed:{brief:'Greed, materialism, or financial mismanagement.',detail:'Reversed, the King becomes the miser, the corrupt businessman, or the figure so obsessed with wealth that he has lost touch with everything else.',advice:'If money has become your identity, you are bankrupt in ways that matter more. If financial management is failing, get expert help before pride destroys what you built.'},
    scores:{fire:0,water:0,air:0,earth:5,spirit:0,beginning:0,growth:0,mastery:5,completion:4}}
];
