// Swords - Air element (14 cards)
const SUIT = 'The Suit of Swords belongs to the element of Air, governing intellect, truth, conflict, communication, and the power of the mind to both liberate and wound.';
const EL = 'swords';

export const SWORDS = [
  { id:'s1', name:'Ace of Swords', num:1, suit:EL, keywords:['clarity','breakthrough','truth','mental power'],
    symbol:{layers:['outerCircle','triUp','rays','dot'],rayCount:6},
    colors:{primary:'#4a6080',secondary:'#7a90a8',accent:'#c0d0e0'},
    deckPosition:'The root energy of the Swords suit. The pure seed of mental clarity.',
    suitMeaning:SUIT, numerology:'One is pure potential. In Swords, it is the moment of absolute mental clarity, the single thought that cuts through confusion.',
    astrology:'Associated with the air signs (Gemini, Libra, Aquarius) in their sharpest, most direct form.',
    foolsJourney:'A new understanding arrives. The mind receives a breakthrough that changes everything.',
    selfPerception:'You see yourself as someone who has just grasped a fundamental truth. The fog has lifted.',
    worldOutlook:'The world is suddenly clear. A veil has been removed and you can see what was hidden.',
    upright:{brief:'A breakthrough of clarity. The truth cuts through everything.',detail:'The Ace of Swords shows a hand emerging from clouds gripping a crowned sword wreathed in laurel and olive. This is the moment of absolute mental clarity: a new idea, a revelation, or a truth that cannot be unseen.',advice:'Act on the clarity while it is fresh. Speak the truth even if your voice shakes. The challenge is following through on what you now see clearly. The caution is against weaponizing truth. The sword cuts both ways.'},
    reversed:{brief:'Confusion, misinformation, or truth used as a weapon.',detail:'Reversed, the sword is dulled or wielded destructively. Mental clarity is blocked, or clarity is being used to hurt rather than illuminate.',advice:'If confused, simplify. Strip away everything that is not essential until the truth becomes visible. If you are using truth to wound, ask whose pain you are really expressing.'},
    scores:{air:10, n1:10}},

  { id:'s2', name:'Two of Swords', num:2, suit:EL, keywords:['indecision','stalemate','denial','blocked emotion'],
    symbol:{layers:['outerCircle','cross','dottedInner','crescent','dot']},
    colors:{primary:'#3a4a60',secondary:'#5a6a80',accent:'#8a9aaa'},
    deckPosition:'The second stage: the mind encounters a choice it cannot resolve through logic alone.',
    suitMeaning:SUIT, numerology:'Two is duality and choice. In Swords, it is the paralysis that comes from seeing both sides too clearly.',
    astrology:'Moon in Libra. Emotional avoidance disguised as balanced deliberation.',
    foolsJourney:'The Fool faces a decision that logic alone cannot resolve. Both options have merit; both have cost.',
    selfPerception:'You see yourself as stuck between two truths. Your identity is suspended in indecision.',
    worldOutlook:'The world presents impossible choices. Logically, both options seem equally valid. Emotionally, you have blocked your feelings to avoid the discomfort of choosing.',
    upright:{brief:'A decision awaits, but you are blocking yourself from making it.',detail:'The Two of Swords shows a blindfolded figure holding two crossed swords, the ocean behind her. She has deliberately blocked her sight, refusing to see the situation clearly because clarity would force a painful choice.',advice:'Remove the blindfold. You already know what you need to do; you are avoiding it because it will hurt. The challenge is accepting that some decisions have no pain-free option. The caution is against mistaking avoidance for neutrality.'},
    reversed:{brief:'Information overload or a forced decision.',detail:'Reversed, the blindfold slips. You are suddenly flooded with information, or external circumstances are forcing the choice you tried to avoid.',advice:'If information is overwhelming, filter for relevance. If the choice is being forced, trust that the universe is removing your ability to stall for a reason.'},
    scores:{air:10, n2:10}},

  { id:'s3', name:'Three of Swords', num:3, suit:EL, keywords:['heartbreak','sorrow','painful truth','grief'],
    symbol:{layers:['outerCircle','triDown','dottedInner','dot'],rotation:180},
    colors:{primary:'#4a2a3a',secondary:'#6a4a5a',accent:'#9a7a8a'},
    deckPosition:'The third stage: truth arrives and it wounds the heart.',
    suitMeaning:SUIT, numerology:'Three is expression. In Swords, it is the expression of a painful truth that cannot be taken back.',
    astrology:'Saturn in Libra. The harsh lesson that not all relationships or beliefs survive honest examination.',
    foolsJourney:'The truth revealed by the Ace pierces the heart. Knowledge has a cost.',
    selfPerception:'You see yourself as wounded by knowledge. Your identity includes the scar of a truth you wish you did not know.',
    worldOutlook:'The world has delivered a painful truth. Logically, you understand why. Emotionally, understanding does not ease the pain.',
    upright:{brief:'A painful truth pierces the heart. Feel it fully.',detail:'The Three of Swords shows three swords piercing a red heart against a stormy sky. This is the card of heartbreak, betrayal, or painful truth. The wound is real and it needs to be felt, not intellectualized.',advice:'Do not bypass the grief with logic. "I understand why it happened" is not the same as healing from it. Feel the pain. The challenge is not hardening your heart in response. The caution is against using pain as justification for cruelty.'},
    reversed:{brief:'Beginning to heal or repressing pain that needs expression.',detail:'Reversed, the swords are slowly withdrawing. Healing begins, or the pain has been pushed so deep it festers.',advice:'If healing, be patient with yourself. If repressing, let it out. Unfelt pain becomes bitterness.'},
    scores:{air:10, n3:10}},

  { id:'s4', name:'Four of Swords', num:4, suit:EL, keywords:['rest','recovery','contemplation','solitude'],
    symbol:{layers:['outerCircle','square','dottedInner','cross','dot']},
    colors:{primary:'#2a3a4a',secondary:'#4a5a6a',accent:'#7a8a9a'},
    deckPosition:'The fourth stage: after the wound, rest and recovery are essential.',
    suitMeaning:SUIT, numerology:'Four is stability. In Swords, it is the enforced rest that follows mental or emotional exhaustion.',
    astrology:'Jupiter in Libra. The expansion that comes through stillness and inner restoration.',
    foolsJourney:'The Fool lies down to recover. The battles of the mind require intervals of stillness.',
    selfPerception:'You see yourself as someone who needs to stop. Your identity is temporarily set aside in favor of recovery.',
    worldOutlook:'The world can wait. Logically, you know rest is not laziness. Emotionally, you need silence.',
    upright:{brief:'Rest. Recovery is not optional; it is the strategy.',detail:'The Four of Swords shows a knight lying in repose within a church, three swords on the wall, one beneath him. This is sacred rest, not laziness. The mind has been working overtime and needs to be still.',advice:'Step away. Meditate, sleep, or simply stop thinking for a while. The challenge is allowing yourself to rest in a culture that equates busyness with worth. The caution is against resting so long that rest becomes avoidance.'},
    reversed:{brief:'Restlessness, burnout, or forced back into action too soon.',detail:'Reversed, rest is either impossible or has been cut short. You are being pushed back into the fray before you are ready.',advice:'If you cannot rest, find micro-moments of stillness. If you are being forced back prematurely, set whatever boundaries you can. You will break if you do not bend.'},
    scores:{air:10, n4:10}},

  { id:'s5', name:'Five of Swords', num:5, suit:EL, keywords:['defeat','conflict','hollow victory','betrayal'],
    symbol:{layers:['outerCircle','star5','dottedInner','crossSmall'],rotation:180},
    colors:{primary:'#3a3a4a',secondary:'#5a5a6a',accent:'#8a8a9a'},
    deckPosition:'The fifth stage: conflict produces a winner, but the victory is hollow.',
    suitMeaning:SUIT, numerology:'Five is disruption. In Swords, it is the conflict where nobody truly wins.',
    astrology:'Venus in Aquarius. The disconnect between intellectual victory and emotional cost.',
    foolsJourney:'The Fool wins a battle but loses something more important. The cost of being right is examined.',
    selfPerception:'You see yourself as either the victor who feels empty or the defeated who feels wronged.',
    worldOutlook:'The world rewards winners, but this victory tastes like ash. Logically, you won. Emotionally, something is broken.',
    upright:{brief:'A hollow victory or a conflict where everyone loses.',detail:'The Five of Swords shows a smirking figure collecting swords from two retreating opponents. He has won, but at what cost? This is the card of arguments won at the expense of relationships, battles that leave all parties diminished.',advice:'Ask yourself: what did this victory actually cost? If you won, was it worth the damage? If you lost, is the defeat truly as devastating as it feels? The challenge is choosing between being right and being at peace. The caution is against punishing others for your own frustration.'},
    reversed:{brief:'Reconciliation after conflict or walking away from a fight.',detail:'Reversed, the battle ends through withdrawal or reconciliation. You may be choosing peace over winning.',advice:'If reconciliation is possible, approach it with humility. If walking away is the only option, do so without looking back.'},
    scores:{air:10, n5:10}},

  { id:'s6', name:'Six of Swords', num:6, suit:EL, keywords:['transition','moving on','healing journey','mental relief'],
    symbol:{layers:['outerCircle','wave','dottedRing','triUp','dot'],dots:6},
    colors:{primary:'#3a5a6a',secondary:'#5a7a8a',accent:'#8aaaba'},
    deckPosition:'The sixth stage: leaving troubled waters for calmer shores.',
    suitMeaning:SUIT, numerology:'Six restores balance. In Swords, it is the movement from turbulence toward peace.',
    astrology:'Mercury in Aquarius. The mental clarity that guides you out of difficult territory.',
    foolsJourney:'The Fool boards a boat and leaves the battlefield behind. Not all healing happens in place; sometimes you must travel toward peace.',
    selfPerception:'You see yourself as someone in transit. Your identity is between chapters, leaving pain behind but not yet arrived at peace.',
    worldOutlook:'The world is moving from worse to better. Logically, you see the path ahead. Emotionally, you carry grief but also quiet hope.',
    upright:{brief:'You are moving toward calmer waters. The transition is underway.',detail:'The Six of Swords shows a ferryman guiding a woman and child across choppy waters toward calm. Six swords stand in the bow. This is the card of necessary transitions, moving from difficulty toward peace. The journey is not over, but the worst is behind you.',advice:'Keep moving forward. Do not go back to retrieve what you left. The challenge is patience during the crossing. The caution is against pretending the journey is over when you are still on the water.'},
    reversed:{brief:'Stuck in transition or return to troubled waters.',detail:'Reversed, the boat is stalled or circling back. You may be unable to leave, or you may be returning to a situation you already escaped.',advice:'If stuck, ask what is anchoring you to the shore you are leaving. If returning, examine whether you are going back for something genuine or out of habit.'},
    scores:{air:10, n6:10}},

  { id:'s7', name:'Seven of Swords', num:7, suit:EL, keywords:['strategy','deception','stealth','shortcuts'],
    symbol:{layers:['outerCircle','star5','dottedInner','crossSmall','dot'],rotation:36},
    colors:{primary:'#4a4a5a',secondary:'#6a6a7a',accent:'#9a9aaa'},
    deckPosition:'The seventh stage: the mind turns to strategy, but strategy can become deception.',
    suitMeaning:SUIT, numerology:'Seven is seeking. In Swords, the search for solutions can lead to shortcuts and deception.',
    astrology:'Moon in Aquarius. The detached cleverness that can rationalize dishonesty.',
    foolsJourney:'The Fool tries to be clever. Strategy is valuable, but when does cleverness cross into dishonesty?',
    selfPerception:'You see yourself as someone who works smarter, not harder. But you may be avoiding honest confrontation.',
    worldOutlook:'The world rewards cleverness. Logically, efficiency justifies the approach. Emotionally, something feels off.',
    upright:{brief:'Strategy or deception. Are you being clever or dishonest?',detail:'The Seven of Swords shows a figure sneaking away from a camp carrying five swords, two left behind. He may be a thief, a spy, or a strategist. This card asks you to examine whether your approach is genuinely strategic or avoidant.',advice:'If strategy is needed, use it with integrity. If you are cutting corners or avoiding difficult conversations, ask what you are afraid of facing directly. The challenge is the line between smart and dishonest. The caution is against self-deception: the person most easily fooled by your rationalizations is you.'},
    reversed:{brief:'Getting caught or coming clean.',detail:'Reversed, the deception is exposed, or you are choosing to be honest after a period of evasion.',advice:'If caught, own it completely. Partial confessions make things worse. If you are coming clean voluntarily, do so fully.'},
    scores:{air:10, n7:10}},

  { id:'s8', name:'Eight of Swords', num:8, suit:EL, keywords:['restriction','imprisonment','self-limitation','victim mentality'],
    symbol:{layers:['outerCircle','dottedInner','cross','rays','dot'],rayCount:8},
    colors:{primary:'#2a2a3a',secondary:'#4a4a5a',accent:'#6a6a8a'},
    deckPosition:'The eighth stage: the mind creates its own prison.',
    suitMeaning:SUIT, numerology:'Eight is power. In Swords, the power of the mind is turned against itself, creating mental cages.',
    astrology:'Jupiter in Gemini. Overthinking that expands problems rather than solving them.',
    foolsJourney:'The Fool stands blindfolded and bound, surrounded by swords. But the bindings are loose. The prison is mental, not physical.',
    selfPerception:'You see yourself as trapped. Your identity is defined by limitation. But the limitation may be self-imposed.',
    worldOutlook:'The world is closing in. Logically, you see no exit. Emotionally, you feel helpless and afraid. But look again: are the walls real?',
    upright:{brief:'You feel trapped, but the cage is your own creation.',detail:'The Eight of Swords shows a blindfolded, loosely bound figure surrounded by eight swords. Water pools at her feet. She could remove the blindfold. She could step between the swords. But she believes she is trapped, and so she is.',advice:'Remove the blindfold. Question the beliefs that tell you there is no way out. The challenge is recognizing that your sense of helplessness is a thought, not a fact. The caution is against waiting for rescue. No one can remove a blindfold you are choosing to wear.'},
    reversed:{brief:'Breaking free from self-imposed limitations or deeper entrapment.',detail:'Reversed, the blindfold is slipping. You are beginning to see that the prison was constructed by your own mind.',advice:'Take the first step, even if it is tiny. Freedom arrives through action, not through more thinking about action.'},
    scores:{air:10, n8:10}},

  { id:'s9', name:'Nine of Swords', num:9, suit:EL, keywords:['anxiety','nightmares','worry','mental anguish'],
    symbol:{layers:['outerCircle','dottedInner','rays','crossSmall','dot'],rayCount:9},
    colors:{primary:'#1a1a2a',secondary:'#3a3a4a',accent:'#5a5a6a'},
    deckPosition:'The ninth stage: the mind tortures itself in the dark hours.',
    suitMeaning:SUIT, numerology:'Nine is near completion. In Swords, the mental journey reaches its darkest point just before dawn.',
    astrology:'Mars in Gemini. Mental energy turned into anxiety and restless, spiraling thought.',
    foolsJourney:'The Fool sits up in bed, head in hands, haunted by the swords on the wall. The night is always darkest before the dawn.',
    selfPerception:'You see yourself through the worst possible lens. Your identity is consumed by worry, guilt, or fear.',
    worldOutlook:'The world is a source of threat. Logically, you know your fears may be exaggerated. Emotionally, that knowledge does not help at 3 AM.',
    upright:{brief:'Anxiety and worry are consuming you. The fear is worse than reality.',detail:'The Nine of Swords shows a figure sitting up in bed, face in hands, nine swords hanging on the wall behind them. This is the card of anxiety, insomnia, guilt, and the spiral of catastrophic thinking. The suffering is real, but it is being amplified by the mind.',advice:'Get out of your head. Talk to someone. Write down the fears and examine them in daylight. The challenge is breaking the spiral. The caution is against normalizing this level of anxiety as "just how I am." You deserve help.'},
    reversed:{brief:'Peak anxiety breaking or reaching out for help.',detail:'Reversed, the nightmare reaches its climax and begins to fade, or you are finally reaching out for the help you need.',advice:'If the worst has passed, be gentle with yourself as you recover. If you are seeking help, follow through. The first step is the hardest.'},
    scores:{air:10, n9:10}},

  { id:'s10', name:'Ten of Swords', num:10, suit:EL, keywords:['rock bottom','ending','betrayal','dawn'],
    symbol:{layers:['outerCircle','cross','rays','dottedRing','triDown','dot'],rayCount:10,rotation:180},
    colors:{primary:'#0a0a1a',secondary:'#2a2a3a',accent:'#4a4a5a'},
    deckPosition:'The tenth and final numbered stage: the mind hits absolute bottom, but dawn is breaking.',
    suitMeaning:SUIT, numerology:'Ten completes the cycle. In Swords, it is the dramatic end that clears the way for a new beginning.',
    astrology:'Sun in Gemini. Illumination arriving after the darkest intellectual and emotional ordeal.',
    foolsJourney:'The Fool lies face down with ten swords in their back. But look at the horizon: golden light is breaking through. This is the end, not the eternal state.',
    selfPerception:'You see yourself as completely defeated. But this is not a permanent identity; it is a moment.',
    worldOutlook:'The world has done its worst. Logically, it can only get better from here. Emotionally, numbness may precede recovery.',
    upright:{brief:'Rock bottom. But the dawn is visible on the horizon.',detail:'The Ten of Swords shows a figure lying face down with ten swords in their back, but golden light breaks at the horizon. This is as bad as it gets, and that is actually the good news. You have hit bottom, which means the only direction now is up.',advice:'Let this be the ending. Do not resurrect what has been so thoroughly destroyed. The challenge is surrendering to the fall rather than fighting it on the way down. The caution is against dramatic suffering. The pain is real, but martyrdom is a choice.'},
    reversed:{brief:'Beginning to rise from the worst or prolonging an ending.',detail:'Reversed, you are either pulling the swords out and beginning to rise, or you are refusing to let the ending be final.',advice:'If you are rising, go slowly. If you are prolonging the pain, ask what you gain from staying down. Sometimes the ground is comfortable because you are afraid of standing.'},
    scores:{air:10, n10:10}},

  { id:'s11', name:'Page of Swords', num:11, suit:EL, keywords:['curiosity','new ideas','vigilance','communication'],
    symbol:{layers:['outerCircle','triUp','starSmall','dot']},
    colors:{primary:'#5a6a80',secondary:'#7a8a98',accent:'#a0b0c0'},
    deckPosition:'The Page is the student of air: curious, sharp, and eager to learn.',
    suitMeaning:SUIT, numerology:'Pages represent the beginning of a new relationship with their element. In Swords, it is the young mind discovering the thrill of ideas.',
    astrology:'Earth of Air. Grounding intellectual energy into concrete questions and observations.',
    foolsJourney:'A new relationship with truth and intellect begins. The mind is sharp and eager.',
    selfPerception:'You see yourself as someone with a keen mind and insatiable curiosity. Your identity is defined by your questions.',
    worldOutlook:'The world is full of information waiting to be gathered and analyzed.',
    upright:{brief:'A sharp new idea or message arrives. Stay alert.',detail:'The Page of Swords stands on a windswept hill, sword raised, scanning the horizon. He is alert, curious, and mentally agile. This card brings new ideas, messages, or the beginning of an intellectual pursuit.',advice:'Follow the curiosity. Ask the questions. The challenge is depth: do not skim the surface of many ideas at the expense of mastering one. The caution is against using your sharp tongue to wound.'},
    reversed:{brief:'Gossip, scattered thinking, or all talk, no follow-through.',detail:'Reversed, the Page uses his sharp mind for gossip, deception, or mental games rather than genuine inquiry.',advice:'Direct your mental energy toward creation, not destruction. A sharp mind without purpose becomes a weapon against yourself.'},
    scores:{air:10, page:10}},

  { id:'s12', name:'Knight of Swords', num:12, suit:EL, keywords:['ambition','speed','directness','charged forward'],
    symbol:{layers:['outerCircle','triUp','rays','diamond','dot'],rayCount:6},
    colors:{primary:'#3a4a60',secondary:'#5a6a80',accent:'#8a9ab0'},
    deckPosition:'The Knight is air in motion: fast, direct, and sometimes cutting.',
    suitMeaning:SUIT, numerology:'Knights represent active pursuit. In Swords, it is the relentless charge toward truth or conquest.',
    astrology:'Air of Air. Pure mental energy in action, the debater and the crusader.',
    foolsJourney:'The mind charges forward with conviction. The Knight does not question; he acts on his beliefs with total commitment.',
    selfPerception:'You see yourself as someone who cuts through nonsense. Your identity is defined by directness and intellectual courage.',
    worldOutlook:'The world responds to decisive action and sharp communication.',
    upright:{brief:'Charge forward with conviction. Speed and clarity are your allies.',detail:'The Knight of Swords gallops at full speed, sword raised, cutting through the wind. He is brilliant, fast, and unstoppable. This card appears when rapid, decisive action based on clear thinking is required.',advice:'Move quickly and speak directly. The challenge is distinguishing conviction from stubbornness. The caution is against leaving a trail of wounded people behind you. Speed without compassion is just aggression.'},
    reversed:{brief:'Reckless words or mental energy without direction.',detail:'Reversed, the Knight charges without thinking, or his sharp tongue cuts people who did not deserve it.',advice:'Slow down. Your words are weapons whether you intend them to be or not. Think before you speak, especially when angry.'},
    scores:{air:10, knight:10}},

  { id:'s13', name:'Queen of Swords', num:13, suit:EL, keywords:['perceptive','independent','clear boundaries','honest'],
    symbol:{layers:['outerCircle','triUp','innerCircle','dottedRing','dotLarge']},
    colors:{primary:'#4a5a6a',secondary:'#6a7a8a',accent:'#9aaaba'},
    deckPosition:'The Queen has mastered air from within. She sees clearly and speaks truthfully.',
    suitMeaning:SUIT, numerology:'Queens represent internal mastery. In Swords, it is the ability to perceive truth without being destroyed by it.',
    astrology:'Water of Air. Emotional intelligence that sharpens intellectual perception.',
    foolsJourney:'The mind has been tempered by experience. The Queen does not flinch from truth; she uses it to protect and liberate.',
    selfPerception:'You see yourself as someone who sees clearly. Your identity is rooted in honesty, independence, and the refusal to be deceived.',
    worldOutlook:'The world needs clear eyes and honest voices. You see through pretense and name what others will not.',
    upright:{brief:'See clearly and speak honestly. Your perception is your power.',detail:'The Queen of Swords sits on her throne, sword raised, facing the observer directly. She has known loss and used it to sharpen her perception rather than harden her heart. She is fair, honest, and unafraid of uncomfortable truths.',advice:'Speak the truth with precision and compassion. Set clear boundaries. The challenge is remaining compassionate when clarity reveals painful realities. The caution is against becoming so guarded that no one can reach you. Clarity without connection is just isolation.'},
    reversed:{brief:'Cold judgment or harsh words masking pain.',detail:'Reversed, the Queen\'s clarity becomes cruelty. Her pain expresses itself as cutting remarks or emotional unavailability.',advice:'If you are being harsh, ask what wound you are protecting. The sword is for clarity, not punishment.'},
    scores:{air:10, queen:10}},

  { id:'s14', name:'King of Swords', num:14, suit:EL, keywords:['intellectual authority','justice','clear judgment','ethical leadership'],
    symbol:{layers:['outerCircle','triUp','cross','rays','hexagon','dotLarge'],rayCount:6},
    colors:{primary:'#2a3a4a',secondary:'#4a5a6a',accent:'#7a8a9a'},
    deckPosition:'The King is the external master of air: the judge, the leader who governs with intellect and fairness.',
    suitMeaning:SUIT, numerology:'Kings represent external mastery. In Swords, it is the authority figure who judges with wisdom and impartiality.',
    astrology:'Fire of Air. Passionate commitment to truth, justice, and intellectual integrity.',
    foolsJourney:'Air has been fully mastered. The King does not just think clearly; he creates systems of fairness and accountability.',
    selfPerception:'You see yourself as a fair and principled thinker. Your identity is tied to intellectual integrity and ethical leadership.',
    worldOutlook:'The world needs clear thinking and fair judgment. You see the role of structure and ethics in human flourishing.',
    upright:{brief:'Judge fairly, think clearly, lead with integrity.',detail:'The King of Swords sits on his throne, sword raised vertically, his gaze steady and impartial. He is the judge, the strategist, the intellectual authority who leads through the power of clear and fair thinking.',advice:'Apply your mind with integrity. Make decisions based on principle, not preference. The challenge is remaining humane while being analytical. The caution is against becoming so detached that you forget the people behind the problems.'},
    reversed:{brief:'Abuse of intellectual power or tyrannical judgment.',detail:'Reversed, the King uses his mental authority to dominate, manipulate, or render unfair judgments.',advice:'Power without compassion is tyranny. If your intellect is being used to control rather than serve, you have lost the crown.'},
    scores:{air:10, king:10}}
];
